MPAS-Dev/MPAS-Analysis

.gitignore, config.analysis, mpas_analysis/ocean/ohc_timeseries.py, mpas_analysis/ocean/sst_timeseries.py, mpas_analysis/sea_ice/timeseries.py, run_analysis.py
- Changed scripts (including the run script and the config file) to optionally skip the visualization of pre-processed ACME-v0 data.
- Added config.analysis_* and config.analysis.* to .gitignore.
=> Re-introduced the option to turn off comparison with ACMEv0 pre-processed data

run_analysis.py
Results from this merge should be identical to the previous version of the run script and the refractor is in preparation to help meet needs in issues, e.g., #20.
=> Refractors run_analysis to support generalization

mpas_analysis/shared/containers.py, mpas_analysis/shared/io/__init__.py, mpas_analysis/shared/io/namelist_streams_interface.py, mpas_analysis/test/__init__.py, mpas_analysis/test/test_namelist_streams_interface.py, mpas_analysis/test/test_namelist_streams_interface/namelist.ocean, mpas_analysis/test/test_namelist_streams_interface/streams.ocean
This is a prototype reader / writer for interfacing with namelist and streams and this will ultimately be needed to support generalization identified in #20. 
A list of preliminary features (included or could be included):
=> Adds namelist and streams file interface

mpas_analysis/shared/io/__init__.py, mpas_analysis/shared/io/utility.py, mpas_analysis/test/test_io_utility.py
Allows path expansion via bash-style expansion:
For example:
```python
from mpas_analysis.shared.io import paths
paths('a*','b*', 'c*')
= ['a1.txt', 'a2.txt', 'b.txt', 'c0.txt', 'c1.txt']
```
This is needed to generalize input to xarray.open_mfdataset:
`ds = xr.open_mfdataset(paths('*year3[0-9]*nc', '*year40*nc'), ...)`
=> Adds path function to simplify xarray open_mfdataset calls

mpas_analysis/configuration/MpasAnalysisConfigParser.py
If a default is provided, the getWithDefault method now correctly
sets the value of the option to the default, rather than trying
to get the value.
=> Fix getWithDefault in MPASAnalysisConfigParser

.travis.yml, ci/install_python.ps1, ci/requirements-py27.yml
Continuous integration using pytest will help us avoid bugs and ensure that design objectives are being met via test.  
This merge adds the capability for Travis CI to run py.test to ensure that tests are passing.
=> Adds travis continuous integration (CI) for pytest

mpas_analysis/shared/mpas_xarray/mpas_xarray.py
The reference start date for time series data has been corrected.
It is now year=yearoffset+1, month=1, day=1, rather than
year=yearoffset, month=12, day=31.  The previous reference date
would lead to the date being the expected start date (e.g.
01/01/1850) only after one day of simulation has elapsed, which
is not the desired behavior.
Also, makes mpas_xarray.py PEP8 compliant.
=> Fix offset date in mpas_xarray

ci/requirements-py27.yml
Ensures that matplotlib is available for testing of mpas_xarray, e.g., see https://github.com/MPAS-Dev/MPAS-Analysis/pull/47#issuecomment-264892670
=> Adds matpltlib to CI req for mpas_xarray testing

run_analysis.py
In the process, a variable name was changed because it has the same name as a function being imported later (to prevent potential conflicts).
=> Make run_analysis.py PEP8 compliant

mpas_analysis/ocean/ocean_modelvsobs.py
this fixes the inconsistency in the 0-index python.  I have looked through the other files and the bug only appears here.
=> Fixes bug in SST bias plots

mpas_analysis/ocean/ohc_timeseries.py, mpas_analysis/ocean/sst_timeseries.py, mpas_analysis/sea_ice/timeseries.py, mpas_analysis/shared/timekeeping/Date.py, mpas_analysis/test/test_date.py
This merge updates the 3 time-series analysis scripts to make use
of the time series start and end dates, computed via `timeseries_yr1`
and `timeseries_yr2`, allowing analysis of a subset of the output
data.
To accomplish this, this merge adds the method `to_datetime` to 
the `Date` class. This method can be used (optionally with an offset
year) to convert a Date to a datetime object.  The date is
clamped to  the valid range supported by numpy's datetime64[ns], 
used by xarray and pandas.
=> Fix time-series scripts use time bounds properly

mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/ocean/ohc_timeseries.py, mpas_analysis/ocean/sst_timeseries.py, mpas_analysis/ocean/variable_stream_map.py, mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/sea_ice/timeseries.py, mpas_analysis/sea_ice/variable_stream_map.py, mpas_analysis/shared/io/namelist_streams_interface.py, mpas_analysis/shared/mpas_xarray/mpas_xarray.py, mpas_analysis/shared/timekeeping/Date.py, mpas_analysis/test/test_date.py, mpas_analysis/test/test_mpas_xarray.py, run_analysis.py
This merge adds dictionaries that can be used to map between the names of variables and streams used internally in MPAS-Analysis to the associated names used in various versions of MPAS dycores.  This helps with cross-compatibility with various MPAS and ACME versions.
mpas_xarray has been modified to include the ability to find the MPAS dycore name of a variable in a data set given the MPAS-Analysis name and the associated map.  mpas_xarray can also now rename variables in a dataset from their MPAS dycore names to those used by MPAS-Analysis using the same map.
The streams file reader has been augmented to include a function that informs the user if a given stream is present, allowing analysis scripts to find the correct name of a given stream using the streams mapping dictionary.
=> Map variables and streams from MPAS dycore names to MPAS-Analysis names

config.analysis, mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/ocean/variable_stream_map.py, run_analysis.py
This adds a comparison to Aquarius monthly observations.  This has been tested against beta0 in the updateTimeseries branch.  This is a clean PR against develop.  I retested against an alpha8 run and things appear to be working.  My config.analysis for testing on edison is at /global/homes/l/lvroekel/config.analysis_SSS_edisontest
=> Adds SSS model vs obs capability

mpas_analysis/sea_ice/timeseries.py
This merge fixes the starting time of the replicate_cycle function
used to repeat sea-ice climatology data sets.  The start time was
not correct if the comparison data set did not start at the same
time as the first cycle of the repeated data set.
=> Fix start time in replicte_cycle for sea-ice data

mpas_analysis/shared/io/namelist_streams_interface.py
Ensures that paths read in streams files are valid.
An error is reported if the path in the streams file
does not exist.
This is important for analysis of ACME files that have
been moved from their original locations because
the path in the streams files may no longer be relevant.
=> Returns error for invalid path in streams file

mpas_analysis/sea_ice/timeseries.py
Previously, the `ds.merge(dsmesh)` resulted
in appending a 0 to the end of ds.Time
This error was noticed in https://github.com/ACME-Climate/PreAndPostProcessingScripts/pull/24
and resulted in errors like
```python
> ds.Time
<xarray.DataArray 'Time' (Time: 13)>
array([Timestamp('1850-01-16 11:30:00.041639'),
Timestamp('1850-02-14 22:23:34.373481'),
Timestamp('1850-03-16 09:35:48.508036'),
Timestamp('1850-04-15 20:30:00.166638'),
Timestamp('1850-05-16 07:37:44.719058'),
Timestamp('1850-06-15 18:28:00.251360'),
Timestamp('1850-07-16 05:39:40.930080'),
Timestamp('1850-08-16 04:39:40.971746'),
Timestamp('1850-09-15 15:24:00.379138'),
Timestamp('1850-10-16 02:41:37.182768'),
Timestamp('1850-11-15 13:22:00.463860'),
Timestamp('1850-12-16 00:43:33.393789'), 0], dtype=object)
Coordinates:
Time …
```
=> Fixes a faulty merge that corrupts ds.Time

mpas_analysis/ocean/ohc_timeseries.py
This resolves an issue where a run directory is moved from one machine
to another, assuming that there is a restart file that is available.
This helps avoids the issue where fields like refBottomDepth,
maxLevelCell, refLayerThickness, etc are not in a mesh file but
must instead be obtained from a separate file
=> Use restart file over input file for vertical mesh

mpas_analysis/sea_ice/modelvsobs.py
sea ice concentration values plotted range from 0.0-1.0, but currently 
the colorbar is labeled as '%'.  This merge changes the label to 'fraction'.
Fixes #70
=> Change sea ice concentration colorbar label to 'fraction'

mpas_analysis/ocean/ohc_timeseries.py, mpas_analysis/ocean/sst_timeseries.py, mpas_analysis/sea_ice/timeseries.py
This PR improves the plotting of time series as well as solves some issues with plotting
ACME v0 timeseries (when available). Specifically, these are the two changes introduced here:
1) a check has been included about whether the v1 time series brackets the times of the v0 results. If time_start is greater than the last time stamp for which v0 data is available, then v0 time series are not plotted;
2) the ohc timeseries has been updated to always start from year 1. This is because OHC is intended to be calculated as anomaly with respect to the heat content of the very first year of the simulation. If timeseries_yr1 is different than simulation year 1, the OHC time series is adjusted to still start from year 1.
=> Improved plotting of timeseries

mpas_analysis/shared/mpas_xarray/mpas_xarray.py, mpas_analysis/test/test_mpas_xarray.py
This merge ensures that datasets returned following subseting 
via mpas_xarray are non-empty.
Previously, it would be possible to provide an argument
of onlyvars that would result in an empty dataset.  This
can result in difficult bugs to find and consquently
we assert that variable subsets via `subset_variables`
do not return empty datasets.
=> Ensures that subseted datasets are non-empty

config.analysis, mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/sea_ice/timeseries.py
ocean_modelvsobs has been changed to read an ocean restart file
instead of a meshfile, consistent with ocean/timeseries.
seaice/timeseries has been changed to first try to load a sea-ice
restart file, then an ocean restart file (raising an exception if
neither exists).  Also, only a small subset of the data from the
restart file is loaded (latCell, lonCell and areaCell) before
the dataset is merged with the time-varying sea ice data.
The mpas_meshfile option has been removed from the default config
file.
=> Switch meshfile to ocean (or sea ice) restart file

mpas_analysis/shared/timekeeping/Date.py, mpas_analysis/test/test_date.py
This merge fixes a bug in Date.to_timedelta  where the local variable day is used instead of self.day.
Also, fix some PEP8 issues in Date.
=> Fix bug in Date.to_timedelta 

design_docs/template.md
This merge adds a template design document for MPAS-Analysis contributions.
=> Adds an example markdown design doc template

mpas_analysis/test/test_mpas_xarray.py
The test is now compatible with xarray 0.9.1, which handles
indexing with so called "dimensions without coordinates"
differently from previous versions.
=> Fix mpas_xarray test for selvals

mpas_analysis/configuration/MpasAnalysisConfigParser.py, mpas_analysis/test/test_mpas_config_parser.py, mpas_analysis/test/test_mpas_config_parser/config.analysis
This merge allows numpy commands to be  used as the values
in config key-value pairs.  This is beneficial because long
arrays are now easily specified, e.g., `np.arange(0,1,100)`.
=> Specify and apply numpy commands in config files

mpas_analysis/configuration/MpasAnalysisConfigParser.py, mpas_analysis/test/test_mpas_config_parser.py, mpas_analysis/test/test_mpas_config_parser/config.analysis
Prevents use of system built in variables by restricting
string to exclude `__` for use in numpy evaluation.
=> Increased safety for config with numpy eval

mpas_analysis/ocean/ocean_modelvsobs.py
This fixes an indexing error in `ocean.ocean_modelvsobs` when plotting mixed layer depth that occurs in xarray 0.9.1.
=> Add month coord in MLD observations

design_docs/config-file_reorganization.md
A design document describing reorganization of the config file for increased clarity and to make it easier to control which analyses are run.
=> Design Document: Config File Reorganization 

design_docs/timekeeping_reorg.md
A design document for reorganizing the timekeeping module.
=> Design Document: reorganizing timekeeping

config.template, configs/edison/config.20161117.beta0.A_WCYCL1850.ne30_oEC.edison, configs/lanl/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison, configs/lanl/config.20170120.beta0.GMPAS-QU240.wolf, configs/olcf/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison, mpas_analysis/sea_ice/modelvsobs.py
I have moved the definition of the seaice concentration and thickness observational filenames from the main routine (modelvsobs) to the config file.
I have also updated all example config files to reflect this change.
This PR addresses #106.
=> Define iceConc/iceThick filenames in config rather than in modelvsobs

mpas_analysis/ocean/ohc_timeseries.py
Previously, when the first year is not part of the analysis range,
the correct files were being selected but the time dimension was
not being sliced properly to only include the first year.
=> Fix time slicing of first year in OHC

mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/ocean/ohc_timeseries.py, mpas_analysis/ocean/sst_timeseries.py, mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/sea_ice/timeseries.py, mpas_analysis/shared/generalized_reader/generalized_reader.py, mpas_analysis/shared/mpas_xarray/mpas_xarray.py, mpas_analysis/test/test_generalized_reader.py, mpas_analysis/test/test_generalized_reader/example_jan.nc, mpas_analysis/test/test_generalized_reader/example_jan_feb.nc, mpas_analysis/test/test_mpas_xarray.py
This merge moves the capability to map variable names (used in MPAS-Analysis to support multiple MPAS and ACME versions as seamlessly as possible) out of `mpas_xarray` to a new `generalized_reader` module.
Both `mpas_xarray` and `generalized_reader` have functions, `open_multifile_dataset`, that can be used in place of existing calls to `xarray.open_mfdataset`.  These functions hide the complications of using a preprocessing function.  `generalized_reader.open_multifile_dataset` adds the capabilities to map variables and to select only 'Time' values between a given start and end date.
These changes have been made to allow MPAS files to be preprocessed in various ways without explicitly having to add complicating functionality to `mpas_xarray` itself.  After these changes, the thought is …
=> Move variable mapping out of mpas_xarray into new generalized_reader module

design_docs/generalize_calendar.md
This design doc describes the requirements, design, implementation and testing of an alternative approach for the time dimension of xarray data sets in MPAS-Analysis that can support either MPAS calendar ('gregorian' or 'gregorian_noleap').
=> Design Document: Generalize Calendar supported by Analysis

ci/requirements-py27.yml, config.template, configs/edison/config.20161117.beta0.A_WCYCL1850.ne30_oEC.edison, configs/lanl/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/olcf/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison, mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/ocean/ohc_timeseries.py, mpas_analysis/ocean/sst_timeseries.py, mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/sea_ice/timeseries.py, mpas_analysis/shared/generalized_reader/generalized_reader.py, mpas_analysis/shared/io/namelist_streams_interface.py, mpas_analysis/shared/mpas_xarray/mpas_xarray.py, mpas_analysis/shared/plot/plotting.py, mpas_analysis/shared/timekeeping/utility.py, mpas_analysis/test/test_generalized_reader.py, mpas_analysis/test/test_mpas_xarray.py, mpas_analysis/test/test_timekeeping.py
This merge modifies mpas_xarray and generalized_reader to produce a 'Time' coordinate that is the floating-point number of days since 0001-01-01.
This merge also updates some of the case/underscore conventions in the timekeeping module to use mixed case (CamelCase) for variable and function argument names.
The 5 analysis scripts have been updated to perform date computations by converting 'Time' coordinates to datetime objects (using `days_to_datetime`) and using the calendar-aware `MpasRelativeDelta` class for computations with offsets in time.
The `yearOffset` config option has been eliminated.  New confg options have been added for selecting a range of dates to be used to create an SST climatology.
A config file for an MPAS-SeaIce test case has been added, showing that a run with start …
=> Replace the Time coordinate in MPAS xarray datasets to days since 0001-01-01

mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/sea_ice/timeseries.py
Several of the sea ice scripts require ocean streams file to be present that will not be for sea ice stand alone simulations. Altered code so that they are not opened unless necessary.
=> Removed necessity of having ocean streams file for seaice analysis

mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/constants/constants.py
This merge moves 5 blocks of code from `ocean_modelvsobs` into 5 functions in `shared/climatology/climatology.py`:
* `compute_monthly_climatology`
* `init_model_interpolation`
* `init_observations_interpolation`
* `interpolate_model_climatology`
* `interpolate_observation_climatology`
The same code is now used to compute monthly and seasonal climatologies in `seaice_modelvsobs`.
This reorganization is also intended to make it easier to change the approach used for performing horizontal interpolation, which is not isolated to the shared climatology module.
=> Modularize ocean and sea ice climatology computations

mpas_analysis/configuration/MpasAnalysisConfigParser.py, mpas_analysis/test/test_mpas_config_parser.py
Since data type bool is also part of `numbers.Integral`, `MpasAnalysisConfigParser.getWithDefault` was previously trying to treat bool types as integers.  This fix puts the check for bool type before that of integer types so bools will get handled correctly.
Also, this merge performs a small amount of PEP8 cleanup of `MpasAnalysisConfigParser`.
New unit tests have been added to ensure that `getWithDefault` behaves as expected.
=> Fix handling of bool in config parser getWithDefault

mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/sea_ice/timeseries.py
`StreamsFile` has no `close` method, so calls have been removed.
`seaice_modelvsobs` now resorts to an ocean restart file if no sea-ice restart file is available.  This is similar to the behavior of `seaice_timeseries`.
Fixes PEP8 formatting in sea ice analysis.
=> Fix bug in sea ice analysis with oceanStreams

mpas_analysis/sea_ice/timeseries.py
Fixes a bug where replicate_cycle in seaice_timeseries was allowing extra copies of the replicated data set to extend as much as a year beyond the end of the data set it is meant to be compared with.  Now, the replicated data set is clipped to the time values that are closest to the beginning and end of the target data set.
=> Fix bounds of results from replicate_cycle

config.default, mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/shared/plot/plotting.py
The over/under arrows now have a different color if additional indices into the color map are provided for these values.
A utility function has been created in ocean_modelvsobs for making the color maps (including under/over values).
A small bug has been fixed in plotting, and some old, commented-out code has been removed.
Previously, the under and over on the bias map were set to black and white respectively.  Now, the behavior is that the under and over for model, observations and bias mpas take the first and last colors in the color map.  If a sufficient number of indices into the colorbar are provided (the number of contour values + 1), the under and over have unique colors.  If fewer colors are provided (usually the number of contour values - 1), the under and over have the same …
=> Fix colorbars for ocean climatology bias maps

mpas_analysis/shared/interpolation/interpolate.py
This merge adds a check for `ESMF_RegirdWeightGen` and `ncremap` before attempting to run those two commands.  It raises an `OSError` with a clearer error message pointing out that the latest `nco` (and its dependency `esmf`) should be installed.
=> Check for esmf and nco before performing interpolation

config.default, configs/edison/config.20161006bugfix.alpha8.A_WCYCL1850S.ne30_oEC_ICG.edison, configs/edison/config.20161117.beta0.A_WCYCL1850.ne30_oEC.edison, configs/edison/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/lanl/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison, configs/lanl/config.20170120.beta0.GMPAS-QU240.wolf, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/olcf/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.titan, mpas_analysis/ocean/meridional_overturning_circulation.py, mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/ocean/variable_stream_map.py, mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/sea_ice/timeseries.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/constants/constants.py, mpas_analysis/shared/plot/plotting.py, run_analysis.py
This PR is intended to accomplish the following:
1) add a general meridional_overturning_circulation script, which will eventually plot both the results of the MOC analysis member (if enabled) and/or the postprocessed MOC, for the global ocean and for a selected number of oceanic basins. Presently, it supports the computation and plotting of the postprocessed MOC only.
2) add a plot_vertical_section routine in the plotting module, meant to plot an MPAS vertical slice (as lat vs z, lon vs z, or spherical distance vs z) using the native MPAS grid (no vertical or horizontal interpolation).
3) modify plotting to make it PEP8 compliant.
=> Add moc script (postprocessing) and plot_vertical_section

mpas_analysis/ocean/meridional_overturning_circulation.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/generalized_reader/generalized_reader.py
This merge switches the file caching of the MOC time-series computation to use a single file instead of one file per year.  This makes it easier to continue the time series into incomplete years (as would often happen if one were running the analysis as the simulation is in progress). The cache file is written out each year to ensure that progress is not lost if the analysis gets interrupted, since the computation is relatively slow.
The merge also includes a few clean-up tasks:
* some PEP8 compliance fixes
* breaking the MOC postprocessing into 2 functions, one for climatology and one for time series
* adding the ability to pass keyword arguments to `open_multifile_dataset`, which let me test if chunking would improve the MOC climatology's memory performance (it didn't)
* removing the …
=> Update MOC time series file caching

config.default, configs/edison/config.20161006bugfix.alpha8.A_WCYCL1850S.ne30_oEC_ICG.edison, configs/edison/config.20161117.beta0.A_WCYCL1850.ne30_oEC.edison, configs/edison/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/lanl/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison, configs/lanl/config.20170120.beta0.GMPAS-QU240.wolf, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/olcf/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.titan, mpas_analysis/ocean/nino34_index.py, mpas_analysis/ocean/nino34_timeseries.py, mpas_analysis/shared/constants/constants.py, mpas_analysis/shared/plot/plotting.py, run_analysis.py
This adds NINO34 functionality.  It computes the NINO34 index following the standard algorithm (e.g. Trenberth 1997) it also computes the power spectra, along with the 95 and 99% confidence intervals (using a chi-squared test).  A red noise best-fit is also included.  This algorithm follows closely what is used in NCL.  
It has been tested on a g-case on anvil and beta0 and beta1 on edison.
=> Adds capability for NINO34 index and spectra plots

mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/sea_ice/modelvsobs.py
If the data set doesn't cover the bounds given by startYear and
endYear, update them in the config file and use the true start
and end years available in the data set.
This should avoid situations where the user chooses a climatology range that is beyond the end of the data set and the figures have misleading title text and file names.
=> Update and save climatology startYear and endYear

README.md, config.default
Make clear that each test case should be given a unique output baseDirectory and that only config options different than the defaults need to be included in a custom config file.
=> Clarify usage in README and config.defaults

mpas_analysis/shared/interpolation/interpolate.py
Previous error message of 
```
OSError: ESMF_RegridWeightGen not found. Make sure esmf package is installed via
latest nco: 
conda install nco
```
requires additional step of including conda-forge channel for conda install so that the error message needs to be instead:
```
OSError: ESMF_RegridWeightGen not found. Make sure esmf package is installed via
latest nco: 
conda install -c conda-forge nco
```
This is essentially a one-liner PR.
=> Improves error message for installation of nco

config.default, mpas_analysis/ocean/meridional_overturning_circulation.py, mpas_analysis/ocean/nino34_index.py, mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/ocean/ohc_timeseries.py, mpas_analysis/ocean/sst_timeseries.py, mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/sea_ice/timeseries.py, mpas_analysis/sea_ice/utility.py, mpas_analysis/shared/analysis_task.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/io/utility.py, run_analysis.py
This requires new input subdirectories for run, ocean history, and sea ice history.  It also requires a separate `StreamsFile` object for output in run and in history subdirectories in each analysis task.
A new helper function has been added under `shared/analysis_task.py` to set up the common functionality of all tasks.  Additional setup common to all sea ice tasks has been added in `sea_ice/utility.py`
The `buildConfigFullPath` function has been changed to `build_config_full_path` everywhere.
A `make_directories` utility function has been added to make  all directories in a path if they don't already exist.
=> Add support for short-term archiving

mpas_analysis/ocean/meridional_overturning_circulation.py, mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/shared/climatology/climatology.py
Add a function to update the `startYear` and `endYear` config options based on the start and end of a climatology data set.  A warning is issued if the start and end years are different from those requested by the user.
All analysis tasks for computing climatologies now use this function to make sure plot titles and file names use the start and end years of the data set (as opposed to those requested in the config file).  The MOC cache file name now uses the actual start and end years as well.
=> Update start and end dates from climatology data set; issue a warning

configs/lanl/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison, configs/lanl/config.20170106.B-EC60to30wLI_with_double_count.wolf, configs/lanl/config.20170120.beta0.GMPAS-QU240.wolf, mpas_analysis/ocean/meridional_overturning_circulation.py
Add a new config file for the `B-EC60to30wLI_with_double_count` run that @JeremyFyke has been running.
Update the locations of mapping files and Atlantic MOC mask files for 2 other LANL configurations.
Update MOC computations to have a try/except around namelist option checks (which were crashing for older ACME versions such as used in `B-EC60to30wLI_with_double_count`).
=> Update LANL configs, add new config for ACME B case with land-ice cavities

config.default, mpas_analysis/ocean/meridional_overturning_circulation.py, mpas_analysis/shared/generalized_reader/generalized_reader.py, mpas_analysis/shared/mpas_xarray/mpas_xarray.py, mpas_analysis/test/test_generalized_reader.py
This specifies a maximum chunk size for each multifile dataset that is opened to avoid dask out of memory errors.
=> Fixes dask out of memory error (sets max chunks)

mpas_analysis/ocean/meridional_overturning_circulation.py
A quick fix to the start and end year in MOC plots that were not being updated properly when the real bounds are different from the requested bounds.
=> Uses updated start and end years for climo plot

mpas_analysis/ocean/ohc_timeseries.py, mpas_analysis/ocean/sst_timeseries.py, mpas_analysis/sea_ice/timeseries.py
Since data from the preprocessedReferenceRun is not always plotted (depending on whether its temporal range overlaps with that of the mainRun), it is easier to remove the `preprocessedReferenceRun` string from the timeseries file names.
This was the cleanest way to address a problem in ACME PreAndPostProcessing, when the html index file is generated: since the `generate_html` script is independent from the python scripts, it always looks for a certain figure name, no matter what MPAS-Analysis generates. Removing the option of having preprocessedReferenceRun in the filename makes things consistent.
=> Removed preprocessedReferenceRunName from timeseries figure names

config.default, mpas_analysis/ocean/meridional_overturning_circulation.py, mpas_analysis/ocean/nino34_index.py, mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/ocean/ohc_timeseries.py, mpas_analysis/ocean/sst_timeseries.py, mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/sea_ice/timeseries.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/constants/constants.py, mpas_analysis/shared/generalized_reader/generalized_reader.py, mpas_analysis/shared/time_series/time_series.py, mpas_analysis/test/test_climatology.py, mpas_analysis/test/test_generalized_reader.py, run_analysis.py
This merge performs caching of all time series and climatology calculations.
The climatology caching can be performed at a frequency set by the config option `yearsPerCacheFile`, which defaults to 1 (meaning results are cached every year).  Once these climatology results are cached, they are aggregated together to compute the full climatology.  The aggregation process is much faster than the original caching, meaning subsequent climatology calculations will be substantially faster even if the start and/or end years of the climatology calculation change.
The time series caching is performed in a single file, which is updated periodically (yearly for MOC; every 10 years for other, faster time-series analysis tasks).  As with the climatology caching, time-series caching is smart enough to …
=> Cache progress on all analysis tasks

config.default, configs/edison/config.20161006bugfix.alpha8.A_WCYCL1850S.ne30_oEC_ICG.edison, configs/edison/config.20161117.beta0.A_WCYCL1850.ne30_oEC.edison, configs/edison/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, mpas_analysis/configuration/MpasAnalysisConfigParser.py, mpas_analysis/ocean/meridional_overturning_circulation.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/generalized_reader/generalized_reader.py, mpas_analysis/shared/mpas_xarray/mpas_xarray.py, mpas_analysis/test/test_mpas_config_parser.py, mpas_analysis/test/test_mpas_config_parser/config.analysis
Simplifies chunking capability and allows for chunking to explicitly be defined for
`open_multifile_dataset`.  Defaults to not performing chunking unless specified in a 
particular configuration file for the MOC case.  Note, this sets a chunking parameter for all edison runs for the MOC.
=> Improve chunking capability

config.default, mpas_analysis/ocean/nino34_index.py, mpas_analysis/shared/constants/constants.py, mpas_analysis/shared/plot/plotting.py
This commit is to add observations to the Nino 34 analysis.  There are three data sources available presently.  Each Nino plot (time series and spectra) has three plots: full record Obs, 1976-2016 Obs, Model.  Here are examples from the beta1_2 run
=> Adds observational panels to Nino34 analysis

mpas_analysis/ocean/meridional_overturning_circulation.py
A previous commit to address stylistic choices in how MOC time series was computed led to incorrect argument order in the function `_compute_moc_time_series_part`.  Apparently this didn't get tested before it got merged (I think we may be rushing too much!).
The error was that constructing a function with the `partial` tool means that the order of arguments is first those passed in to partial explicitly, then those added on when the function created by partial is called (https://docs.python.org/2/library/functools.html#functools.partial), whereas I had assumed the opposite.
=> Fix MOC time series caching

mpas_analysis/ocean/meridional_overturning_circulation.py, mpas_analysis/ocean/nino34_index.py, mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/ocean/ohc_timeseries.py, mpas_analysis/ocean/sst_timeseries.py, mpas_analysis/ocean/variable_stream_map.py, mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/sea_ice/timeseries.py, mpas_analysis/sea_ice/utility.py, mpas_analysis/sea_ice/variable_stream_map.py, mpas_analysis/shared/analysis_task.py, mpas_analysis/shared/io/namelist_streams_interface.py, run_analysis.py
These dictionaries are used to map namelist options between different MPAS versions, analogous to `variableMaps` for variable names and `streamsMaps` for stream names.
Adds a function `check_analysis_enabled` to `analysis_task` that can be used to check if an analysis member is enabled and optionally raise an exception if it is not.
=> Add namelist maps

mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/time_series/time_series.py, mpas_analysis/test/test_climatology.py
This merge adds a unit test for the `cache_climatologies` function.  The unit test computes and caches a climatology computed on 3 months of data.  The climatology is computed both with caching every 1 year and every 2 years.  The resulting climatology is verified against a reference solution in each case.  Checks are made to ensure that the file(s) produced have the expected names and that they are either modified or left unmodified by a second call to `cache_climatologies`, depending on whether each cache file is considered to be "complete".
The `cache_climatologies` function has been broken into 3 non-public helper functions.
A few small bugs related to the names of cache files have been fixed.  Previously, the final "individual" cache file was being named after the actual range of …
=> Add unit test for cache_climatologies

mpas_analysis/shared/climatology/climatology.py, mpas_analysis/test/test_climatology.py
`totalDays` and `totalMonths` was previously being computed incorrectly
because the months were not being masked to only `monthValues`.
This did not affect the computation of the climatologies themselves
in general, just the cache file.
=> Fix the month masking for climatology caching

mpas_analysis/shared/time_series/time_series.py
Previously, if a user changed the range over which a time series was being computed, the cache files could end up with time values that were not in ascending order.  This has been fixed.
=> Keep Time dim sorted during time series caching

mpas_analysis/ocean/meridional_overturning_circulation.py
If the velocity climatology covers only 1 year, the name being loaded was previously not
correct (e.g. `meanVelocity_years0001-0001.nc` instead of `meanVelcoity_year0001.nc`),
leading to an error that the file was not found.
=> Bug fix: name of mean velocity climatology when analyzing only one year

mpas_analysis/ocean/ocean_modelvsobs.py, mpas_analysis/sea_ice/modelvsobs.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/test/test_climatology.py
In cases where the single cached climatology file has the same name as the aggregate climatology file, we don't need to aggregate. We also want to make sure to close open data sets to prevent conflicts when writing to files of the same name (though this situation hopefully is avoided in any case).
Previously, files containing a single year of climatology data were being given a suffix like `years0001-0001`.  This has now been fixed for greater consistency, to prevent redundant copies of the same data set from being written, and to prevent occasional "permission denied" errors when trying to write the same file.
Unnecessary save operations after file caching in the `modelvsobs` tasks have been removed to save time and prevent "permission denied" errors.
A helper function `_get_year_string` …
=> Fix errors with caching climatologies

design_docs/remapper.md
A design document describing the new `MeshDescriptor` and `Remapper` classes.
=> Add Remapper design document

mpas_analysis/test/test_climatology.py
If the test runs too fast, the date modified can't be used to
make sure the unit test has passed.  This merge adds a 1-second
delay to make sure a modified file has a different time stamp
after modification than before.
I also fixed a typo in one variable name and an extraneous line from a previous version of the test.
=> Fix check for modified files in clim. unit test

config.default, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan, mpas_analysis/shared/climatology/climatology.py
Use of *.compute() was dangerous because it required
xarray / dask to store arrays in memory, which is problematic
for large problem sizes like the 18to6.  For the MOC
calculation for the 18to6, use of `maxChunkSize` is required to
ensure that the large arrays fit into memory for the climatology
calculation.  However, for smaller problem sizes (60to30)
use of `maxChunkSize` will result in a performance penalty relative
to this value being None because computations will be faster if
arrays fit into memory.
=> Fixes MOC for 18to6 on titan

mpas_analysis/shared/generalized_reader/generalized_reader.py
This occurs only when opening the data set with open_multifile_dataset
and after clipping the time dimension to be between the desired
start and end dates.
=> Raise error when data set has no Time entries

README.md, ci/requirements-py27.yml, config.default, configs/README.md, configs/edison/job_script.edison.bash, configs/job_script.default.bash, configs/lanl/config.20170120.beta0.GMPAS-QU240.wolf, configs/lanl/job_script.lanl.bash, configs/olcf/job_script.olcf.bash, mpas_analysis/ocean/climatology_map.py, mpas_analysis/sea_ice/climatology_map.py, mpas_analysis/shared/interpolation/remapper.py, run_analysis.py
Parallel task are controlled with the `parallelTaskCount` and `commandPrefix` options in the new `execute` section of the config file.  By default `parallelTaskCount = 1` (serial execution) and `commandPrefix=` (i.e. no prefix). `commndPrefix` can be used to add a prefix such as `srun -n 1` or a path to python if needed.
If there is more than one task to run and `parallelTaskCount > 1`, several tasks run in parallel, and their output is stored in log files instead of being output to stdout/stderr.
The configuration after each task is complete (whether run serially or in parallel) is written out to a config file named `config.<taskName>` in the log folder.  This documents the configuration (though not in a terribly user-friendly way, since config option names are case insensitive and …
=> Add support for running tasks in parallel

mpas_analysis/shared/io/namelist_streams_interface.py
The code currently assumes input namelists are lowercase. This change allows non-lower case namelists to work.
=> Allowed non-lower case namelists

mpas_analysis/shared/analysis_task.py
The path is now be relative to the baseDirectory, not to the
runDirectory, as specified in the comment in config.default.
This error was not detected in MPAS-Analysis tests because they
all use the same baseDirectory and runDirectory, but the same
is not true of A-Prime.  Probably a standard test that simulates
ACME short-term archiving is needed.
=> Fix path to namelist files

mpas_analysis/ocean/climatology_map.py, mpas_analysis/ocean/index_nino34.py, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_ohc.py, mpas_analysis/ocean/time_series_sst.py, mpas_analysis/sea_ice/climatology_map.py, mpas_analysis/sea_ice/time_series.py, mpas_analysis/shared/generalized_reader/generalized_reader.py, mpas_analysis/shared/io/namelist_streams_interface.py, mpas_analysis/test/test_namelist_streams_interface.py
With this merge, each task gets a list of files from the appropriate stream during its `setup_and_check` phase.  If no files are found within the appropriate time range (i.e. between the startYear and endYear for a climatology, time series or climate index), an exception is raised to say that no files were found.
This new behavior is intended to provide a clearer error message when a user selects a range for which no files are available.
Three other small bugs have been fixed along the way:
* in the `streamfunctionMOC` task, when the climatology start and end years are updated based on the range of the actual climatology, the copy of the start and end years stored in the task itself (`self.startYearClimo` and `self.endYearClimo`) are now also updated.  This ensures that the task attempts …
=> Check if files are found within requested time range

mpas_analysis/configuration/MpasAnalysisConfigParser.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/test/test_mpas_config_parser.py
The `getExpression` method from the `MpasAnalysisConfigParser` was
returning `None` when the config option was not present.  This was
confusing when the option was not intentionally left out, leading
to non-intuitive error messages.  Now, `getExpression` will raise
a `NoOptionError` (as do all `get*` methods) when the option is missing.
To accommodate the special needs of chunking, the `chunking` option
of the generalize reader has been set to `None` if no chunking is
specified in the config file.
CI tests have been updated accordingly.
=> Fix confusing None return from getExpression

mpas_analysis/ocean/index_nino34.py, mpas_analysis/shared/plot/plotting.py
At least for now, the plotting routines used by the `indexNino34`
task are too specific to that task to be included in the
`shared.plot.plotting` module.  They have been moved to the
`IndexNino34` class instead.
Since these routines rely on functions in `shared.plot.plotting`
that were non-public before, these two routines have been made
public:
* `plot_xtick_format`
* `plot_size_y_axis`
=> Move specific plotting to indexNino34 task

config.default, mpas_analysis/ocean/climatology_map.py, mpas_analysis/ocean/index_nino34.py, mpas_analysis/sea_ice/climatology_map.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/grid/grid.py, mpas_analysis/shared/interpolation/remapper.py, mpas_analysis/shared/io/__init__.py, mpas_analysis/shared/io/utility.py, mpas_analysis/shared/io/write_netcdf.py, mpas_analysis/shared/plot/plotting.py, mpas_analysis/shared/time_series/time_series.py, mpas_analysis/shared/timekeeping/MpasRelativeDelta.py, mpas_analysis/shared/timekeeping/utility.py, mpas_analysis/shared/variable_namelist_stream_maps/ocean_maps.py, mpas_analysis/test/test_analysis_task.py, mpas_analysis/test/test_climatology.py, mpas_analysis/test/test_timekeeping.py, run_analysis.py
This merge performs various types of cleanup to the repo.
It sets the level of output from `ncremap` to a near minimal level.  It suppresses all non-error output from `ESMF_RegridWeightGen`.  
A new function, `shared.io.write_netcdf`, is introduced for writing `xarray` data sets with finite `_FillValue`, taken by default from the `netCDF4` package.  This change makes various NCO calls happier and suppresses warnings about non-finite `_FillValue`.
With these changes, calls to `ncremap` produce output like:
```
Input #00: /media/xylar/extra_data/analysis/output/GMPAS-QU240/simplify_ncremap_output/clim/mpas/mld_oQU240_JAS_years0002-0005.nc
Map/Wgt  : /media/xylar/extra_data/analysis/output/GMPAS-QU240/simplify_ncremap_output/mapping/map_climatologyMapMLD_oQU240_to_0.5x0.5degree_bilinear.nc …
```
=> General clean-up PR

mpas_analysis/shared/climatology/climatology.py
With the change to `write_netcdf`, `ncremap` now extrapolates with
bilinear remapping but does not normalize by default.  This leads
to values closer to zero than expected in extrapolated regions.
When we do not use `ncremap`, we renormalize these values based on
only the weights of unmasked source grid cells.  With this merge,
we do the same when using `ncremap`.
=> Renormalize climatologies also when using ncremap

config.default, mpas_analysis/sea_ice/climatology_map.py, mpas_analysis/shared/plot/plotting.py
The subplots can be arranged vertically if the config option `vertical=True`.  The vertical layout is less useful on a screen that is wider than it is tall, so the change is meant for easier viewing and comparison.
=> Make sea-ice climatology plots horizontal by default

config.default, configs/edison/config.20161006bugfix.alpha8.A_WCYCL1850S.ne30_oEC_ICG.edison, configs/edison/config.20161117.beta0.A_WCYCL1850.ne30_oEC.edison, configs/edison/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/lanl/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison, configs/lanl/config.20170106.B-EC60to30wLI_with_double_count.wolf, configs/lanl/config.20170120.beta0.GMPAS-QU240.wolf, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/olcf/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.titan, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan, mpas_analysis/ocean/climatology_map.py, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/sea_ice/__init__.py, mpas_analysis/sea_ice/climatology_map.py, mpas_analysis/shared/climatology/__init__.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/io/namelist_streams_interface.py, mpas_analysis/test/test_analysis_task.py, mpas_analysis/test/test_climatology.py, run_analysis.py
These are separate tasks for the Arctic and Antarctic and for
concentration and thickness.  This work is helpful for several
subsequent tasks:
* further parallelizing seasons and obseration sources
* writing out XML descriptions of each plot (and using them
to make a webpage
* switching over to `ncclimo`
Also, switches to updating start and end year for climatologies based on available file names, rather than the times in the data sets. This is needed because we need to know the names of the plots that each task will produce (e.g. for HTML generation) without actually opening the associated data set, and the start and end year are included in many climatology file names.
=> Split climatologyMapSeaIceConcThick into 4 tasks 

mpas_analysis/test/test_analysis_task.py
I accidentally pushed a broken CI test and it got merged before we noticed.  This merge fixes the error (where names of sea-ice tasks were changed in some places but not others in the test).
=> fix CI test test_analysis_task

config.default, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/shared/climatology/__init__.py, mpas_analysis/shared/climatology/climatology.py
This merge uses `ncclimo` to compute an annual climatology of velocity, which is subsequently used to compute the MOC streamfunction.
A function for calling `ncclimo` has been added to the `climatology` module, and another has been added for updating `startYear` and `endYear` for climatologies based on the list of files that are actually available.
Since `ncclimo` does not support renaming variables according to the `variableMap`, variables have been manually renamed using the names supported by ACME beta1 and later.
=> MOC with ncclimo

mpas_analysis/ocean/time_series_ohc.py
In cases where the first simulation year was not part of the
time series, the first year was being computed only for the regions
to plot, whereas the time series was being computed for all regions.
This led to a problem when trying to combine the two.
=> Fix bug in OHC time series

mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/interpolation/remapper.py
This prevents NCO from using @czender's local version of NCO instead of our own NCO version on DOE LCF machines.
=> Add NCO_PATH_OVERRIDE='No' before NCO calls

mpas_analysis/shared/plot/plotting.py
There seems to be no such argument
=> Remove spacing='uniform' argument to contourf

README.md, docs/api.rst, run_mpas_analysis
`--list` will list all available analysis tasks (useful for deciding
what to include in the `--generate` flag).  No config file should be
needed. The tags associated with each task are also printed.
`--purge` will delete the base output directory so the analysis can
be run cleanly at that location.  A config file must be supplied
with section [output] and option baseDirectory giving the location
to be deleted.  The user is told whether the location was deleted.
=> Add --list and --purge command-line options

mpas_analysis/config.default
The range for sea ice concentration used to go only to +/- 0.8. Now it goes to +/- 1.0.  Sea-ice thickness now goes to +/- 3.0. I have added 2 color levels to each difference plot, so the colors
of each level have changed slightly.
=> Update the range for diff in sea ice conc. and thick

mpas_analysis/ocean/time_series_ohc.py, mpas_analysis/ocean/time_series_sst.py
In `time_series_sst`, `filePrefix` was defined with the `.png` extension in it, making all filenames have the extra `.png` in them.
This may have been introduced by mistake in one of our latest commits.
=> Fix bug in defining filePrefix for time_series_sst

configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, configs/anvil/job_script.anvil.bash, mpas_analysis/ocean/climatology_map.py, mpas_analysis/sea_ice/climatology_map.py, run_mpas_analysis
In order to support Anvil, we need to move mapping file generation to the `setup_and_check()` phase (so it runs in serial).   We also need to run setup on its own without the mpirun command so that ESMF_RegridWeightGen (which is an mpi program) can run properly.
This merge also adds a job script and config file for analyzing a run on Anvil.
=> Add Anvil support

configs/theta/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, configs/theta/job_script.theta.bash
The theta job script needs an extra step of creating a bash wrapper around `run_mpas_analysis`.  This is because, without the wrapper, the job scheduler creates a symlink to `run_mpas_analysis`, meaning python no longer finds the `mpas_analysis` package.
=> Add a config file and job script for theta

configs/edison/job_script.edison.bash, configs/job_script.default.bash, configs/lanl/job_script.lanl.bash, configs/olcf/job_script.olcf.bash, docs/api.rst, mpas_analysis/analysis_task_template.py, mpas_analysis/ocean/climatology_map.py, mpas_analysis/ocean/index_nino34.py, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_ohc.py, mpas_analysis/ocean/time_series_sst.py, mpas_analysis/sea_ice/climatology_map.py, mpas_analysis/sea_ice/time_series.py, mpas_analysis/shared/__init__.py, mpas_analysis/shared/analysis_task.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/interpolation/remapper.py, mpas_analysis/shared/time_series/time_series.py, mpas_analysis/test/test_analysis_task.py, run_mpas_analysis
In order to support better data availability between tasks (e.g.
if tasks depend on data from the setup of other tasks), tasks are
now subclasses of `multiprocess.Process`.  This work is needed  to
support subtasks (e.g. for producing climatologies, or for generating 
each plot from a task).
Logging is also altered so that each task has a logger, to which
info, errors and warnings should be logged.  Print statements will
automatically go to the logger as "info" while exceptions and
warnings raised through the `warning` module will be logged as
errors.
Because `multiprocess.Process` already uses a method called `run()`,
the `run()` method of `AnalysisTask` and its derived classes had to
be renamed to `run_analysis()`.
=> Switch from subprocess to multiprocessing

configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, configs/edison/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/edison/config.20170807.beta1.G_oQU240.edison, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/lanl/config.MatchBoth_orig, configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan
This should have been part of #224, which switched the code to using a single mapping file directory rather than requiring that all mapping files be specified individually.
=> Switch example config files to use mapping directory

docs/design_docs.rst, docs/design_docs/prerequisite_tasks.md
This design document describes a method for supporting "prerequisite" tasks that need to be run before other analysis tasks can be performed.  This functionality is needed in order to support caching times from multifile data sets and will likely be useful in the future for building up complex tasks from simpler pieces.
=> Add design document describing prerequisite tasks

mpas_analysis/shared/io/write_netcdf.py
Iterating over data sets will no longer iterate over coordinates in addition to data variables.  We want both when we write out NetCDF files, so we switch to doing so explicitly.
=> Fix future warning from xarray

run_mpas_analysis
Previously, the code was not exiting with status 1 when a task failed.
=> Fix exit status when errors occur in tasks in serial mode

configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, configs/edison/config.20170807.beta1.G_oQU240.edison, configs/edison/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/edison/config.20171102.beta3rc02_1850.ne30_oECv3_ICG.edison, configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/lanl/config.MatchBoth_orig, configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan, configs/theta/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, docs/api.rst, mpas_analysis/config.default, mpas_analysis/ocean/__init__.py, mpas_analysis/ocean/climatology_map_antarctic_melt.py, mpas_analysis/ocean/climatology_map_mld.py, mpas_analysis/ocean/plot_climatology_map_subtask.py, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py, mpas_analysis/shared/constants/constants.py, run_mpas_analysis
Observations are from Rignot et al. (2013).
To support masking the melt rate field only where land-ice is present and renormalizing the field to change to units of m/yr, a capability to customize climatologies during the remapping process.
A new directory for the melt observations has been added, along with a new section in the config file for this task.
The new task has been added to the auto-documentation.
`'no_climatologyMapAntarcticMelt'` has been added to `generate` lists for all example config files without land-ice cavities.  This way, users aren't concerned when this task fails during `setup_and_check()`.
=> Add task for plotting climatology maps for Antarctic melt rates

configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, configs/anvil/job_script.anvil.bash, configs/edison/config.20170807.beta1.G_oQU240.edison, configs/edison/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/edison/config.20171102.beta3rc02_1850.ne30_oECv3_ICG.edison, configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/lanl/config.MatchBoth_orig, configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan, configs/theta/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, configs/theta/job_script.theta.bash, mpas_analysis/config.default, mpas_analysis/ocean/streamfunction_moc.py
The name of the MOC mask file is constructed automatically from the
mesh name.
This approach is needed in anticipation of having other region masks (notably masks for individual ice shelves, see #237)
Example config files have been updated accordingly.
=>  Change to mask directory instead of individual mask files

mpas_analysis/shared/time_series/mpas_time_series_task.py
There is a bug when rerunning analysis in python 3 with time series output.  The `xtime_startMonthly` variable was not being converted correctly to a string.  This has been fixed.
=> Fix decoding of string in python 3 when rerunning time series

mpas_analysis/shared/time_series/mpas_time_series_task.py
This merge makes the range of files printed in the log ignore the first year if it is not in the requested range, even though it gets added to allow anomaly computations.
=> Fix first file for time series

mpas_analysis/ocean/index_nino34.py, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/shared/analysis_task.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/plot/plotting.py, mpas_analysis/shared/time_series/mpas_time_series_task.py, mpas_analysis/shared/time_series/time_series.py, mpas_analysis/test/test_mpas_climatology_task.py, run_mpas_analysis
This clean up is needed to generalize the task in preparation for supporting comparison with a reference run (which will replace one of the panels).
A new task has been added to extract time series needed by indices (which may have different time bounds than time series).  Support for separate time bounds was eliminated, perhaps accidentally, in  #271.
Nino34 spectra are now packed into dictionaries for easier iteration and panels are plotted in loops.
The function for determining the maximum value of all spectra (to determine the bounds of the y axes of these plots) has been cleaned up so it no longer relies on a plot already having been performed). 
All warnings previously produced with `warnings.warn` have been switched to just using `print('Warning:..')` because this produces much …
=> Clean up the nino34 index task

configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, configs/edison/config.20170807.beta1.G_oQU240.edison, configs/edison/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/edison/config.20171102.beta3rc02_1850.ne30_oECv3_ICG.edison, configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/lanl/config.MatchBoth_orig, configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan, configs/theta/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, mpas_analysis/config.default, mpas_analysis/shared/analysis_task.py, run_mpas_analysis
This merge adds support for an `only_` prefix in the generate flag, for example:
```
./run_mpas_analysis --generate=only_ocean,only_horizontalMap config.my_run
```
will run only ocean tasks and only those that have the `horizontalMap` tag (climatology maps).  The `only_` prefix works by excluding all tasks that do *not* have that tag.  (If the first item in the `generate` list has the `only_` prefix,  we implicitly add 'all' to the beginning of the `generate` list, because otherwise no tasks would run.)
The output from the `--list` command line argument has been clarified:
* `task: ` has been added in front of each task name to make clear which are tasks and which are tags
* the component for each task is also displayed.
=> Add "only_" prefix to "generate" config option; clarify output from --list command line option

configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl, configs/cori/job_script.cori-haswell.bash, configs/cori/job_script.cori-knl.bash, configs/theta/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, mpas_analysis/config.default, mpas_analysis/ocean/__init__.py, mpas_analysis/ocean/climatology_map_antarctic_melt.py, mpas_analysis/ocean/climatology_map_sose.py, mpas_analysis/ocean/plot_climatology_map_subtask.py, mpas_analysis/ocean/remap_depth_slices_subtask.py, mpas_analysis/ocean/utility.py, mpas_analysis/shared/plot/plotting.py, preprocess_observations/README.md, preprocess_observations/mds.py, preprocess_observations/remap_SOSE_T_S.py, preprocess_observations/remap_rignot.py, run_mpas_analysis
They can be plotted over various seasons and at various depths.
A utility for computing MPAS-Ocean zMid has been added.
`mpas_analysis.ocean.PlotClimatologyMapSubtask` now supports plotting a field at a specified depth.
Scripts for pre-processing Rignot et al (2013) and SOSE observations have been added in the `preprocess_observations` directory.
=>  Add analysis tasks for plotting SOSE T and S

mpas_analysis/shared/time_series/mpas_time_series_task.py
If variables are missing in an existing time series data set, delete the data set and start over rather than trying to append.
=> Check for missing variables in MPAS time series

configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl, configs/edison/config.20170807.beta1.G_oQU240.edison, configs/edison/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/edison/config.20171102.beta3rc02_1850.ne30_oECv3_ICG.edison, configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/lanl/config.MatchBoth_orig, configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan, configs/theta/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, mpas_analysis/config.default, mpas_analysis/ocean/__init__.py, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/shared/constants/constants.py, mpas_analysis/shared/plot/plotting.py, preprocess_masks/make_ice_shelf_masks.py, run_mpas_analysis
This is a continuation of a WIP PR originally submitted by @xylar, for adding the ability to plot time series of submarine melt rates for individual ice shelves. Continued work on this feature is taking place on this fork.
=> Add antarctic melt time series

mpas_analysis/ocean/meridional_heat_transport.py
To save the bother of writing out the MHT stream just for the latitude bins, these bins can now (optionally) be read from the `timeSeriesStatsMonthlyOutut` stream instead.
The `refZMid`, `refBottomDepth` and `refThickness` are read or computed from a restart file instead of the MHT stream.
=> Read meridional heat transport lat bins from either of 2 streams

README.md, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/time_series/mpas_time_series_task.py
This prevents certain issues with very large NetCDF3 files (e.g. from high resolution MPAS-O output).
Without this fix, an error occurs when running analysis on large MPAS files:
```
...
netCDF3 NETCDF_64BIT_OFFSET format limits fixed variables to sizes smaller than 2^32 B = 4 GiB ~ 4.2 GB, and record variables to that size per record.
```
From @czender:
> Since the MPAS input is NETCDF_64BIT_OFFSET, that's what ncclimo uses for the output. However,  `timeMonthly_avg_normalVelocity` is > 8 GB, and exceeds the format constraint. (How MPAS wrote the input dataset without error is...unknown to me, perhaps PnetCDF trickery?).
=> Add -4 flag to force NetCDF4 output format from NCO

mpas_analysis/shared/plot/plotting.py, run_mpas_analysis
Before this merge, the zero line has the same extent as the first (valid) curve being plotted, whereas it should really have the full extent of the axis.
Also adds an error message when a config file is requested but that file doesn't actually exist.  Previously, it seems that no error was raised in such cases and config options were simply read in from those config files that *were* found.
=> Fix zero line in time series

docs/authors.rst, docs/e3sm.rst, docs/index.rst, docs/mpascice.rst, docs/mpaso.rst, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/io/namelist_streams_interface.py, mpas_analysis/shared/io/utility.py, mpas_analysis/shared/time_series/mpas_time_series_task.py, mpas_analysis/test/test_mpas_climatology_task.py
We haven't been testing standalone MPAS-O and MPAS-SeaIce runs on a regular basis.  As a result, they were no longer working and this merge attempts to remedy that situation.
File names produced by standalone MPAS runs don't necessarily conform to E3SM standards, and are therefore not supported by `ncclimo` all versions of NCO.  (`ncclimo` in NCO 4.7.3 will include more general file-name parsing so this could be a partial solution to the problem.)  The solution here is to create symlinks to the timeSeriesStatsMonthlyOutput files in the analysis output directory where the links have the expected E3SM file names.
Additionally, there are 3 places in MPAS-Analysis where years and months are extracted from file names.  Previously, this was done in a lazy way assuming the E3SM file-naming …
=> Support standalone MPAS runs

mpas_analysis/config.default
This was not the case for SST, SSS and MLD, which could lead to
meaningless blue/pink speckle.
=> Change diff color map to be white near zero

mpas_analysis/config.default, mpas_analysis/ocean/__init__.py, mpas_analysis/ocean/climatology_map_ssh.py, mpas_analysis/shared/constants/constants.py, run_mpas_analysis
A task for plotting the SSH vs. observations from AVISO.
=> Add a task for plotting the sea surface height vs. obs

docs/api.rst, mpas_analysis/config.default, mpas_analysis/configuration/mpas_analysis_config_parser.py, mpas_analysis/ocean/climatology_map_ssh.py, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/ocean/plot_climatology_map_subtask.py, mpas_analysis/ocean/plot_hovmoller_subtask.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/sea_ice/plot_climatology_map_subtask.py, mpas_analysis/shared/plot/plotting.py
All these tasks now support a choice of either contours (via indexed color maps) or continuous plotting (via a "norm").  Tick marks can be specified (optionally) differently from contour levels.
Contour lines can also be plotted on top of any plot by specifying contour values, a color for contours and a line width.
These changes generalize and consolidate some redundant code related creating color maps.
The changes also enable a new SSH plot, similar to Maximenko et al. (2009):
=>  Use common color map setup for all plots with color maps

configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, mpas_analysis/config.default, mpas_analysis/ocean/streamfunction_moc.py
By default, the bolus velocity is added as long as GM is turned on.
=> Optionally add bolus velocity to MOC

mpas_analysis/config.default, mpas_analysis/ocean/compute_anomaly_subtask.py, mpas_analysis/shared/time_series/anomaly.py, mpas_analysis/shared/time_series/mpas_time_series_task.py
This is useful for runs that include a spin-up phase and anomalies are only of interest after the spin-up has completed (e.g. the last CORE-II cycle in a G-case E3SM run).
=> Add support for specifying the anomaly ref year

licenses/_headers/license-bump-copyright.sh, licenses/_headers/license-find-missing.sh, licenses/_headers/license-prepend-missing.sh, licenses/_headers/license-setup.sh, mpas_analysis/ocean/climatology_map_argo.py, mpas_analysis/ocean/compute_anomaly_subtask.py, mpas_analysis/ocean/index_nino34.py, mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py, mpas_analysis/ocean/plot_hovmoller_subtask.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_ohc_anomaly.py, mpas_analysis/ocean/time_series_salinity_anomaly.py, mpas_analysis/ocean/time_series_temperature_anomaly.py, mpas_analysis/shared/time_series/anomaly.py, mpas_analysis/shared/time_series/moving_average.py, run_mpas_analysis
This merge moves the encoding headers to the top of python files.  It also updates the code for prepending license headers to make sure encoding headers go before the license header.
A few files have had license headers added to them.
=> Fix encoding headers in python files

mpas_analysis/shared/mpas_xarray/mpas_xarray.py, mpas_analysis/test/test_generalized_reader.py, mpas_analysis/test/test_mpas_xarray.py
This merge converts all variables without the `Time` dimension into coords within mpas_xarray's preprocessor function.  This prevents these variable from being expanded by xarray.open_mfdataset()
to have a Time dimension, which we don't want.
After updating the mpas_xarray unit test to accommodate these changes, it now works as expected with xarray 0.10.3.  It only worked correctly with xarray 0.10.2 and earlier because behavior was inconsistent when opening one file vs. multiple files in `xarray.open_mfdataset()`.
=> Make non-time-dependent vars be coords in mpas_xarray

README.md, configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl, configs/edison/config.20170807.beta1.G_oQU240.edison, configs/edison/config.20171102.beta3rc02_1850.ne30_oECv3_ICG.edison, configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/lanl/config.MatchBoth_orig, configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan, configs/theta/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, docs/mpasseaice.rst, mpas_analysis/config.default
...everywhere except where used by ncclimo and in namelist and streams files in config files for existing E3SM runs.
Following @akturner's work to rename MPAS-Seaice (from MPAS-CICE), we need to make the same update in MPAS-Analysis.  In practice this affects relatively few parts of the code because output file names from E3SM runs are read in from the streams file and we don't happen to use any namelist options that included `cice` in the name.
=> Rename cice to seaice

docs/.gitignore, docs/Makefile, docs/conf.py, docs/environment.yml, docs/index.rst, docs/observations.rst
To avoid a complicated custom build on ReadTheDocs, the 3 obs. tables are now built in conf.py since the Makefile is not used.
The rst files have been renamed for easier readability.  They have been added to `.gitignore`
This merge also includes some minor renaming and re-arranging in the docs.
=> Fix the docs

mpas_analysis/ocean/climatology_map_mld.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/time_series/mpas_time_series_task.py
Before calling NCO tools, raise exceptions if the requested variables are not available so only tasks requesting unavailable variables fail, not the full analysis.
=> Check for requested variables in timeSeriesStatsMonthly

mpas_analysis/config.default, mpas_analysis/ocean/index_nino34.py, mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py, mpas_analysis/ocean/plot_hovmoller_subtask.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/ocean/time_series_sst.py, mpas_analysis/sea_ice/time_series.py, mpas_analysis/shared/plot/plotting.py
A config file can now be used to specify `firstYearXTicks` and
`yearStrideXTicks` to control how ticks are set for a time axis, e.g.:
```
[hovmollerOHCAnomaly]
firstYearXTicks = 2
yearStrideXTicks = 2
[hovmollerTemperatureAnomaly]
firstYearXTicks = 2
yearStrideXTicks = 2
[hovmollerSalinityAnomaly]
firstYearXTicks = 2
yearStrideXTicks = 2
[timeSeriesSeaIceAreaVol]
firstYearXTicks = 2
yearStrideXTicks = 2
[timeSeriesSST]
firstYearXTicks = 2
yearStrideXTicks = 2
[streamfunctionMOC]
firstYearXTicks = 2
yearStrideXTicks = 2
```
=> User-specified tick start and stride for time axes

mpas_analysis/config.default, mpas_analysis/ocean/__init__.py, mpas_analysis/ocean/climatology_map_antarctic_melt.py, mpas_analysis/ocean/climatology_map_ohc_anomaly.py, mpas_analysis/ocean/climatology_map_ssh.py, mpas_analysis/ocean/plot_climatology_map_subtask.py, mpas_analysis/ocean/remap_depth_slices_subtask.py, mpas_analysis/ocean/utility.py, mpas_analysis/shared/climatology/__init__.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/climatology/ref_year_mpas_climatology_task.py, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py, mpas_analysis/shared/plot/plotting.py, mpas_analysis/test/test_mpas_climatology_task.py, run_mpas_analysis
The maps show the OHC (per unit area) integrated over a list of depth ranges (by default 0 to 10,000 m, 0 to 700 m, 700 to 2000 m and 2000 to 10,000 m).  10,000 m is expected to be below the bottom of the ocean in all of our MPAS-O configurations.
=> Add climatology maps for OHC anomalies

README.md, docs/mpaso.rst, docs/mpasseaice.rst, mpas_analysis/config.default
These two files have changed names (again).  The names in E3SM master
are mpaso_in and mpassi_in.  This PR updates those references.
=> Updates mpas-o_in and mpas-seaice_in names

README.md, ci/requirements.yml, conda/recipe/meta.yaml, docs/api.rst, docs/environment.yml, mpas_analysis/config.default, mpas_analysis/ocean/__init__.py, mpas_analysis/ocean/climatology_map_sose_merid_vel.py, mpas_analysis/ocean/climatology_map_sose_vel_mag.py, mpas_analysis/ocean/climatology_map_sose_zonal_vel.py, mpas_analysis/shared/plot/plotting.py, run_mpas_analysis, setup.py
The default color maps for these fields are from the `cmocean` package, so this has been added as a dependency (in a bunch of places!) and the color maps are registered with `matplotlib` as part of our standard handling of color maps.
=> Add tasks for plotting velocity magnitude and components against SOSE 

README.md, config.example, mpas_analysis/config.default, mpas_analysis/ocean/climatology_map_argo.py, mpas_analysis/ocean/climatology_map_mld.py, mpas_analysis/ocean/climatology_map_ohc_anomaly.py, mpas_analysis/ocean/climatology_map_ssh.py, mpas_analysis/ocean/climatology_map_sss.py, mpas_analysis/ocean/climatology_map_sst.py, mpas_analysis/ocean/index_nino34.py, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_ohc_anomaly.py, mpas_analysis/ocean/time_series_salinity_anomaly.py, mpas_analysis/ocean/time_series_sst.py, mpas_analysis/ocean/time_series_temperature_anomaly.py, mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py, mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py, mpas_analysis/sea_ice/time_series.py
The new default is to generate only the tasks with this tag:
```
generate = ['all_publicObs']
```
Any tasks without observations are also given the `publicObs` tag because they will run successfully if someone only has the publicly available observations.
This merge also adds an example config file at the top level with the most common options that a user would want to change.
The README.md has also been updated to clarify creating a custom config file, including mentioning the new example config file.
=> Add a publicObs tag to all tasks with obs. on public server

docs/.gitignore, docs/Makefile, docs/conf.py, docs/observations.rst, docs/parse_table.py, mpas_analysis/obs/observational_datasets.xml, mpas_analysis/ocean/climatology_map_mld.py, mpas_analysis/ocean/climatology_map_sose_mld.py
The page is generated from the XML database and looks almost identical to the `README.md` for each except that it has a link to the bibtex file on the E3SM public repo.
A few things have been done to improve the behavior of `make clean` in the docs
A `nameInDocs` tag has been added to each observation in the data set. This tag is used to name documentation files describing each data set and to create links from the tables to the more detailed
descriptions.
Two instances of the `Authors` section in the docstring have been cleaned up.  These cause distracting warnings when building the documentation.
=>  Add autogenerated page for each obs. data set

README.md, ci/requirements.yml, conda/recipe/meta.yaml, download_analysis_data.py, mpas_analysis/shared/io/download.py, preprocess_observations/preprocess_SOSE_data.py, preprocess_observations/preprocess_Schmidtko_data.py, setup.py
This allows a nice progress bar and should avoid an error seen with urllib.
The script also now checks if the file is already there *and* if it has the right size.  If not, it will be downloaded.
To support the progress bar, it is necessary to no longer use threading, since one cannot easily do separate progress bars for separate threads.
=> Switch scripts that download obs. data to use "requests" package

mpas_analysis/ocean/meridional_heat_transport.py
Quick change in MHT legend text for the observation part. It is confusing to me to just have ECMWF and NCEP in there.
This addresse #372.
=> Update MHT legend text with Trenberth reference

mpas_analysis/shared/plot/plotting.py
A recent change got rid of the legend by mistake when there was only one time series to plot even when observations were present.
=> Fix legend plotting when obs are available

README.md, docs/analysis_tasks.rst, mpas_analysis/config.default, mpas_analysis/obs/observational_datasets.xml, mpas_analysis/ocean/__init__.py, mpas_analysis/ocean/climatology_map_sose_potential_density.py, mpas_analysis/ocean/remap_sose_climatology.py, preprocess_observations/preprocess_SOSE_data.py, run_mpas_analysis
This merge also makes various changes to the script for preprocessing SOSE data:
* switch `depth` to `z` in SOSE output, since it is positive up.  This will mean having to replace SOSE data on all machines once the update is in place. Once we do that, old versions of MPAS-Analysis will break with the new SOSE data. It seems like the change should be made sooner rather than later to avoid this problem once SOSE data is widely used.
* To facilitate computing bottom potential density, `zBot` was added as a coordinate.  A trick was needed to make sure `zBot` gets remapped, since coordinates are not normally remapped.
* There were issues with velocity magnitude on the original lat/lon grid (the 2 components aren't on the same grid) so velocity magnitude is now only available on the Antarctic …
=>  Add SOSE potential density task

README.md, docs/config/climatology.rst, docs/config/observations.rst, docs/configuration.rst, docs/parse_table.py, docs/tasks/climatologyMapSST.rst, docs/tasks/climatologyMapSchmidtko.rst, docs/tasks/climatologyMapSeaIceConcNH.rst, docs/tasks/climatologyMapSeaIceConcSH.rst, docs/tasks/climatologyMapSeaIceThickNH.rst, docs/tasks/climatologyMapSeaIceThickSH.rst, docs/tasks/indexNino34.rst, docs/tasks/timeSeriesSalinityAnomaly.rst, docs/tasks/timeSeriesSeaIceAreaVol.rst, docs/tasks/timeSeriesTemperatureAnomaly.rst, mpas_analysis/config.default, mpas_analysis/obs/make_obs_readme_bibtex.py, mpas_analysis/obs/observational_datasets.xml, mpas_analysis/ocean/climatology_map_argo.py, mpas_analysis/ocean/climatology_map_schmidtko.py, mpas_analysis/ocean/climatology_map_sose_temperature.py, mpas_analysis/ocean/climatology_map_sst.py, mpas_analysis/ocean/index_nino34.py, mpas_analysis/ocean/time_series_temperature_anomaly.py, mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py, mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py, mpas_analysis/sea_ice/time_series.py, run_mpas_analysis
This pull request includes some unrelated clean-up that has been piling up in the issues:
* fix some missing packages in the README
* Generalize indexNino34 to be labeled correctly if a user chooses `nino3` or `nino4` as regions (which never happens, but still...)
* Change temperature to potential temperature in many places (but not in task names, config options or tags, just in docs, comments, captions and titles)
* Move the obs paths/files from [oceanObservations] to [climatologyMapSST] and from [seaIceObservations] to the individual tasks
* Removed empty bibtex files from the documentation and they are also no longer generated by the script that generates the individual obs. README and bibtex files
* Moved [regions], [plots] and [html] toward the top of config.default so the order is …
=> A general clean-up pull request

docs/config/plot.rst, mpas_analysis/config.default, mpas_analysis/ocean/index_nino34.py, mpas_analysis/shared/plot/plotting.py, run_mpas_analysis
We don't use it and it is leading to import issues, since we need to decide whether to use the "Agg" backend before importing functionality from matplotlib.
=> Remove "displayToScreen" option

mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py, mpas_analysis/ocean/time_series_sst.py, mpas_analysis/sea_ice/time_series.py, mpas_analysis/shared/time_series/__init__.py, mpas_analysis/shared/time_series/time_series.py
Some obs. and preprocessed datasets were being opened with `xarray.open_mfdataset()` function (via the the "generalized reader" in MPAS-Analysis), which sometimes led to "too many open files" errors.
=> Update all multifile datasets to use ncrcat

configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, configs/edison/config.20180129.DECKv1b_piControl.ne30_oEC.edison, configs/edison/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix, configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/theta/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, configs/theta/config.20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta, mpas_analysis/config.default, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/ocean/streamfunction_moc.py
This is *very* 'work in progress' for now. I just wanted to open this for discussion of some points.
=> Add script to plot online MOC

mpas_analysis/shared/html/pages.py, run_mpas_analysis
I got tired of seeing a list of 300 tasks and would rather see a progress bar.  I assume this is doubly true for others for whom the names of the tasks aren't necessarily meaningful.
The old list of tasks have been logged to `logs/taskProgress.log`
=> Log task progress to file and instead display progress bar

mpas_analysis/ocean/climatology_map_sose.py
The file prefix was 'temp' for all variable before the fix, which meant tasks where overwriting each other's images and the resulting web page didn't make sense.
=> Fix file prefix for sose climatology task with ref runs

mpas_analysis/shared/plot/plotting.py
This applies only to sea ice plots at the moment.  They had a small (almost imperceptible) gap around +/-180 degrees.  This merge removes that gap.
=> Fix periodic boundary in polar plots of lat/lon data

docs/environment.yml, readthedocs.yml
We're getting out-of-memory errors so trying to reduce the cost.
=> Update docs to python 3.5, simplify build

configs/acme1/config.20180129.DECKv1b_piControl.ne30_oEC.edison, configs/alcf/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, configs/alcf/config.20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta, configs/alcf/job_script.cooley.bash, configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, configs/anvil/job_script.anvil.bash, configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl, configs/cori/job_script.cori-haswell.bash, configs/cori/job_script.cori-knl.bash, configs/edison/config.20180129.DECKv1b_piControl.ne30_oEC.edison, configs/edison/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix, configs/edison/config.20180514.G.oQU240wLI.edison, configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/edison/job_script.edison.bash, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/lanl/config.MatchBoth_orig, configs/lanl/job_script.lanl.bash, configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan, configs/olcf/job_script.olcf.bash, mpas_analysis/obs/analysis_input_files
The config files are now usable from cooley and theta both.
The batch script on theta is no longer useful because of the 128 node requirement.
Example config files have been updated for all machines to:
* remove preprocessed run info
* point to the new diagnostics location (for mapping files, region masks and observations)
* remove some less commonly used sections
Example job scripts have been updated to point to e3sm-unified 1.2.0
In the list of public diagnostics data to download, the names of some mapping files have been corrected while others have been removed, since we do not plan to support the RRS30to10v3 resolution in the public release.
=> Update example config files; fix list of mapping files

configs/alcf/job_script.cooley.bash, configs/anvil/job_script.anvil.bash, configs/cori/job_script.cori-haswell.bash, configs/cori/job_script.cori-knl.bash, configs/edison/job_script.edison.bash, configs/job_script.default.bash, configs/lanl/job_script.lanl.bash, configs/olcf/job_script.olcf.bash
This seems to be necessary to prevent an issue with HDF5 files being locked (e.g. by `ncclimo`).  
This merge also updates the way E3SM-Unified is loaded in the job scripts to use modules instead of sourcing a setup file.  The module approach for loading the conda environment doesn't allow the use of conda commands but all other functionality of the environment seems to work as expected.
=> Disable HDF5 locking in example job scripts

mpas_analysis/ocean/compute_transects_subtask.py
Previously, transects occasionally ended up with redundant points.  With this fix, these redundancies *seem* to be removed.
=> Fix bug in interpolating transect segments

mpas_analysis/config.default, mpas_analysis/ocean/plot_transect_subtask.py, mpas_analysis/shared/plot/plotting.py
Added the ability to compare the model and reference fields on transects by plotting the contours of both fields on a single plot (as an alternative to the default mode of plotting the model and reference fields and their difference as heatmaps on a three panel plot).
New parameters in the [transects] section of config.default control which comparison mode (three panel plot or contour comparison plot) is used, what the line style and line color of contours are (controlled separately for the contours on heatmaps or of the model field on contour comparison plots vs. the contours of the reference field on contour comparison plots), whether to label the contours, and what precision to use for the contour labels.
These parameters can later be moved to the config.default section for specific …
=> Transect contour plots

run_mpas_analysis
Make sure all tasks in the `runningTasks` dictionary have been processed before finishing the tasks loop.  All tasks may be finished (either successfully or not) but we still need to loop through the tasks that have not been popped from `runningTasks` to report errors.
=> Fix error reporting on tasks

mpas_analysis/obs/observational_datasets.xml
EKE has been moved to the end, rather than the beginning of the table of ocean observations.  Formatting and other mistakes have been corrected.  Source and References have been shortened to be consistent with other table entries, with longer entries moved to the description
=> Update observations XML for EKE

README.md, conda/recipe/meta.yaml, mpas_analysis/config.default, mpas_analysis/ocean/sose_transects.py, mpas_analysis/shared/plot/plotting.py
This merge adds a `'none'` option for `contourLevels` options.  This allows contours to be turned off if they are on by default (in `config.default`), which was not possible previously.
SOSE transects are given more useful longitude values and depths, and contours are turned off by default.  JAS and JFM seasons are added for these transects.  Longitudes passed to the SOSE transects task are now sorted to make sure they don't cause errors when trying to index them later in xarray.
This merge also does a little bit of house cleaning, adding missing pyproj and setuptools packages to the conda recipe and readme.
=> Update the location, depth and seasons for SOSE transects

mpas_analysis/test/test_mpas_config_parser.py, mpas_analysis/test/test_mpas_xarray.py, mpas_analysis/test/test_timekeeping.py
This merge uses six to fix the naming incompatibility between python 2 and 3 for the function `assertRaiseRegex(p)`.  Without this fix, CI is failing under python 2.
=> Fix CI under python 2

mpas_analysis/config.default, mpas_analysis/shared/plot/plotting.py
This merge defines colormaps as either `indexed` or `continuous`, meaning users can override indexed colormaps in the default config file with continuous maps in custom config files.
closes #426
=> Explicitly set colormap type (indexed or continuous) in config options

README.md, ci/requirements.yml, conda/recipe/meta.yaml, docs/api.rst, mpas_analysis/__main__.py, mpas_analysis/config.default, mpas_analysis/obs/analysis_input_files, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/shared/html/pages.py, mpas_analysis/shared/regions/__init__.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py
The new subtask, `ComputeRegionMasksSubtask`, takes a geojson file name and an optional list of features from that file to compute masks from.  As before, a mask file can, instead, be provided in the the directory pointed to by the config option `[region]/regionMasksDirectory`.  This can either be a file created by a previous run of MPAS-Analysis or one generated from `MpasMaskCreator.x` in the MPAS-Tools repo.
I updated the `TimeSeriesAntarcticMelt` task to make use of this subtask.  This means that new meshes with land-ice cavities will not need pre-generated region masks before melt time series can be plotted.
=> Add a subtask for computing region masks on the fly

mpas_analysis/__main__.py
When the users gives no arguments, right now they get a couple hundred lines of error messages. Instead it should just call the parser.print_help() method and exit nicely.
=> Catches zero arguments

mpas_analysis/__main__.py, mpas_analysis/config.default, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/shared/analysis_task.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/climatology/ref_year_mpas_climatology_task.py, mpas_analysis/shared/time_series/mpas_time_series_task.py, mpas_analysis/test/test_mpas_climatology_task.py
The subtasks are:
* `ComputeMOCClimatologySubtask` - computes the MOC climatology and stores it to a file
* `PlotMOCClimatologySubtask` - plots the MOC climatology, possibly as a 3-panel plot vs. the climatology from a reference run
* `ComputeMOCTimeSeriesSubtask` - several subtasks that each compute one year of the MOC time series and store the results to a file
* `CombineMOCTimeSeriesSubtask` - combines the results from each `ComputeMOCTimeSeriesSubtask` into a single time series file.
* `PlotMOCTimeSeriesSubtask` - plots the MOC time series, possibly along with the time series from a reference run.
To support breaking the MOC time series computation into multiple tasks, it was necessary to update time bounds (based on what files are actually available) *before* analysis tasks are …
=> Break the MOC into several subtasks

config.example, configs/acme1/config.20180129.DECKv1b_piControl.ne30_oEC.edison, configs/alcf/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, configs/alcf/config.20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta, configs/anvil/config.20170926.FCT2.A_WCYCL1850S.ne30_oECv3.anvil, configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl, configs/edison/config.20180129.DECKv1b_piControl.ne30_oEC.edison, configs/edison/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix, configs/edison/config.20180514.G.oQU240wLI.edison, configs/edison/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/lanl/config.BGCphaeo4.testrun, configs/lanl/config.GMPAS-OECO-ODMS-IAF.oRRS30to10v3, configs/lanl/config.MatchBoth_orig, configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan, docs/config/runs.rst, mpas_analysis/__main__.py, mpas_analysis/config.default, mpas_analysis/ocean/plot_climatology_map_subtask.py
Adds a config option `mainRunConfigFile`.  By pointing to a config file for analysis that has already run
(from which only the output directory and subdirectories are used), the climatologies, time series, mapping files and masks can be reused rather than needlessly recomputing them.
This merge also fixes a string vs. byte issue that occurs when indexing depths in Argo and SOSE climatology maps.  An error occurs when trying to reuse depth data (possibly only in python 3) because byte strings don't compare correctly with unicode strings.
closes #345
=> Allow main vs. ref comparision to use a cached main in addition to a cached ref analysis run

docs/config/input.rst, mpas_analysis/__main__.py, mpas_analysis/config.default, mpas_analysis/shared/generalized_reader/generalized_reader.py, mpas_analysis/test/test_climatology.py, mpas_analysis/test/test_generalized_reader.py
xarray no longer supports this option.
=> Remove code related to deprecated "autoclose" option

mpas_analysis/__main__.py
Older versions of xarray are not supported after #501, which is undesirable and unnecessary.  All that is needed to fix this is to not raise and exception if `file_cache_maxsize` is not supported in a given xarray version.
closes #505
=> Fix unsupported file_cache_maxsize for older xarray

.stickler.yml
Stickler CI makes sure that code is PEP8 compliant, either providing comments if it is not or adding commits to fix code if needed.
closes #507
=> Add support for Stickler CI for python

mpas_analysis/shared/analysis_task.py
An IOError is raised when a namelist or streams file is missing and
this was not getting caught.
=> Fix handling of missing namelist/streams files

ci/requirements.yml, mpas_analysis/__main__.py
The full stack trace is available with the `--verbose` flag
closes #504
=> Make output during setup-and-check phase less verbose

mpas_analysis/ocean/woce_transects.py
This got removed either in the process of adding dates to observations or adding potential density to WOCE transects.
=> Add back missing WOCE transect at Prime Meridian

README.md, mpas_analysis/ocean/climatology_map_ssh.py
This is needed to support weighted averages in time for climatologies  with latest xarray
closes #525
=> Remove time variables from SSH Obs

README.md, ci/requirements.yml, conda/recipe/meta.yaml, mpas_analysis/ocean/compute_transects_subtask.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py, mpas_analysis/shared/grid/grid.py, mpas_analysis/shared/interpolation/remapper.py
While the numpy-based regridder works fine for projeciton grids, it's not as fast as ncremap.
This merge depends on new features in NCO 4.7.9.  Requirements have been updated accordingly.
closes #520
=> Use ncremap on projection grids

readthedocs.yml
This is necessary because latest doesn't support autosummary correctly, see: https://github.com/rtfd/readthedocs.org/issues/4446
=> Revert back to python 3.5 and drop latest ReadTheDocs

README.md, mpas_analysis/__main__.py, mpas_analysis/ocean/climatology_map_ohc_anomaly.py, mpas_analysis/ocean/compute_anomaly_subtask.py, mpas_analysis/ocean/index_nino34.py, mpas_analysis/ocean/streamfunction_moc.py
The anomaly tasks cannot meaningfully run on a year or less of data.  They now all check during setup to see if there is sufficient data an fail with a warning if not.  (The reason for the failure is not given unless the --verbose tag is used.)
Add text telling users to get more info with the `--verbose` tag
Don't overwrite MOC time series if the yearly and total data are the same
Add conda-forge badges (unrelated but a convenient place to do this).
closes #545 
closes #543
=> Check for enough data in anomaly and Nino34 tasks; fix MOC time series with 1 year of data

README.md, ci/requirements.yml, docs/conf.py, docs/environment.yml, mpas_analysis/__main__.py, mpas_analysis/config.default, mpas_analysis/shared/analysis_task.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/grid/grid.py, mpas_analysis/shared/plot/plotting.py, mpas_analysis/test/test_mpas_climatology_task.py, mpas_analysis/test/test_mpas_climatology_task/config.QU240, setup.py
This requires each task to know how many subprocesses it has (1 for most tasks, 12 for ncclimo tasks).  In the future, tasks can also use `dask` or other methods to run multiple threads and the subprocess count can reflect this.
This should also prevent `ncclimo` from trying to run 12 threads while other tasks are running unless more than 12 parallel tasks are allowed via `parallelTaskCount`.
=> Support multiple subprocesses per task (12 for ncclimo in bck mode)

configs/alcf/config.20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta, configs/alcf/config.20190301.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta, configs/alcf/job_script.cooley.30to10.bash, mpas_analysis/__main__.py, mpas_analysis/ocean/climatology_map_ohc_anomaly.py, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/ocean/sose_transects.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py, mpas_analysis/test/test_mpas_climatology_task.py
...instead of `ncclimo`.
The files produced with `xarray`/`dask` drop the `Time` dimension so various subsequent calls that drop the time dimension are no longer needed (except when `ncclimo` is still used).
set the config option
```
[climatology]
useNcclimo = False
```
to use xarray for climatologies.
This PR also reorganizes the way the SOSE transects are preprocessed (so that mapping files can be created for interpolating them).  With the reorganization, preprocessing is faster and uses significantly less memory.
=> Optionally compute climatologies with xarray/dask

README.md
Should be `>=3.0.2`, not `>=3.2.0`, which doesn't exist yet...
=> Fix matplotlib version

mpas_analysis/shared/html/pages.py, mpas_analysis/shared/html/templates/main_page.html
The git hashtag is skipped if not in a github repo.
closes #565
=> Add MPAS-Analysis version and git hashtag to webpage

mpas_analysis/shared/html/image_xml.py, mpas_analysis/shared/html/pages.py, mpas_analysis/shared/html/templates/component_gallery.html, mpas_analysis/shared/html/templates/component_group.html, mpas_analysis/shared/html/templates/component_image.html, mpas_analysis/shared/html/templates/component_page.html, mpas_analysis/shared/html/templates/component_quicklink.html, mpas_analysis/shared/html/templates/component_subtitle.html, mpas_analysis/shared/html/templates/index.js, mpas_analysis/shared/html/templates/main_component.html, mpas_analysis/shared/html/templates/main_page.html, mpas_analysis/shared/html/templates/style.css
This should help with smoother loading of the very large ocean pages because thumbnail sizes are known even before they load.
Also, remove license headers from HTML templates -- they aren't useful.
closes #558
=> Set gallery thumbnail sizes

mpas_analysis/ocean/compute_transects_subtask.py, mpas_analysis/ocean/remap_depth_slices_subtask.py
This just requires transposing (and then transposing back) `nCells` and `nVertLevels` in both cases.
With this update, we can use `ncremap` for all the remapping rather than having special cases that are handled by the internal python remapper.  `ncremap` is expected to be faster and adds a bit more metadata.
closes #524
=> Add ncremap support to climatology depth slices and transects

README.md, ci/requirements.yml, mpas_analysis/config.default, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py
Use them to limit the number of dask threads and "weight" each task
as couting as more than one subprocess
Update the task for computing region masks to set its subprocessCount
to 1 if the mask is already there (no need to block other work
if there's nothing to do).
closes #577
=> Add subprocessCounts and daskTasks to ocean time series tasks

mpas_analysis/__main__.py
Before this fix, if a main vs. ref run was performed with only a subset of the analysiss, the code would attempt to link directories from the main and/or ref runs that didn't exist, causing a crash.  This has been fixed.
closes #568
=> Fix linking of main and reference directories for a main vs. ref run

mpas_analysis/ocean/climatology_map_antarctic_melt.py, mpas_analysis/ocean/climatology_map_bgc.py, mpas_analysis/ocean/climatology_map_eke.py, mpas_analysis/ocean/climatology_map_mld.py, mpas_analysis/ocean/climatology_map_ohc_anomaly.py, mpas_analysis/ocean/climatology_map_ssh.py, mpas_analysis/ocean/climatology_map_sss.py, mpas_analysis/ocean/climatology_map_sst.py, mpas_analysis/ocean/time_series_ocean_regions.py
Many tasks that have `PlotClimatologyMapSubtask`s were incorrectly passing `controlConfig` as the 6th argument, when it is now the 7th. Better to pass arguments by keyword to avoid this problem.
The reference data for the `timeSeriesOceanRegions` task was not being read correctly from a file.
=> Fix main vs. ctrl bugs

mpas_analysis/config.default, mpas_analysis/ocean/plot_transect_subtask.py
Before, they showed the full transect even if the user asked for only part of it.
Also, updated the WOCE comment to identify the 3 transects.
closes #599
=> Fix the WOCE insetis to use user-selected bounds

README.md, docs/api.rst, download_analysis_data.py, download_natural_earth_110m.py, mpas_analysis/__main__.py, mpas_analysis/download_data.py, setup.py
This merge breaks downloading data into a separate module `download_data`.  This prevents `requests` form being imported unless it is needed, since `requests` hangs on the b512 node on Anvil/Blues.
The merge also updates to docs:
* Updates the path to download_analysis_data in the docs.
* Adds missing docs for the `cartopy` download.
* Fix some issues with `README.md` that were causing it not to render right when converted to RST.
=> Isolate requests import

mpas_analysis/obs/analysis_input_files, mpas_analysis/shared/grid/grid.py
This prevents file names that will differ just because of machine-precision differences between machines and also reduces pointlessly long names.
closes #603
=> Round dlat/dlon in mesh names to 3 digits

docs/config/diagnostics.rst, mpas_analysis/config.default, mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/io/utility.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py, mpas_analysis/test/test_climatology.py, mpas_analysis/test/test_mpas_climatology_task/config.QU240, mpas_analysis/test/test_remap_obs_clim_subtask/config.remap_obs
This allows a user to supply their own observations, mapping files or region masks (without putting them in a shared diagnostics directory). This is appropriate when working with custom meshes or testing new observations or regions that aren't (yet) standard in MPAS-Analysis.
In the process of testing, I found bugs in `timeSeriesOceanRegions` that I have fixed here.  They relate to the names of subtasks, which were not unique when a second region group is defined.
closes #604
=> Add customDirectory for diagnostics

mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py
In cases where some features have a given property but others don't,
the property is assigned an empty string so there is one entry per
feature.
closes #619
=> Fix copying properties in mask creation

mpas_analysis/shared/html/image_xml.py, mpas_analysis/shared/html/pages.py
Tasks were failing during writing out the XML files used to generate web pages if the `git` command wasn't available.  It's quite conceivable that people would run on systems where `git` isn't available by default.
=> Handle case where git command is not available

mpas_analysis/ocean/regional_ts_diagrams.py
The ctrl fields were overriding the main, rather than getting added to them.
=> Fix list of plot fields for main vs. ctrl T-S diagrams

mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/generalized_reader/generalized_reader.py, mpas_analysis/shared/mpas_xarray/mpas_xarray.py, mpas_analysis/shared/plot/climatology_map.py
Updates calls to `xarray.open_mfdataset()` to include a new argument, `combine='nested'`, needed for our usage. The desired coordinate (typically `'Time'`) doesn't always exist and needs to be specified. This change gets rid of a large number of deprication warnings.
Also, updates `addcyclic` to make multidimensional index a tuple, getting rid of several `FutureWarning`s in sea-ice tasks.
closes #628
=> Address depricated and future warnings from xarray and numpy

configs/alcf/20190405.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta.yrs41-50.conf, docs/config/climatology.rst, docs/config/dask_treads.rst, docs/tasks/regionalTSDiagrams.rst, docs/tasks/timeSeriesAntarcticMelt.rst, docs/tasks/timeSeriesOceanRegions.rst, mpas_analysis/config.default, mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/time_series/mpas_time_series_task.py
With this merge, users can set the number of subprocesses that each subtask occupies (increasing this number will make sure we don't run out of memory) and separately control the number of dask threads used in these subtasks (more total dask threads, up to the available cpu count, should make the task run faster).
=> Add config to control xarray/dask climatology subtasks

mpas_analysis/shared/analysis_task.py
Previously, an unhelpful error message related to an invalid index resulted when no files were found in a given history stream. This merge attempts to replace that error message with a more helpful one saying which years could not be found in the given component and stream.
=> Clarify error message when files are missing

mpas_analysis/config.default, mpas_analysis/ocean/climatology_map_sose.py, mpas_analysis/ocean/climatology_map_woa.py
In the SOSE and WOA18 climatology maps and only for temperature, salinity and potential density,
not velocities, set up a different color map (with a different range) for shallow depths (above -500 m by default) and deeper depths.
closes #642
=> Separate shallow and deep color maps for some analysis tasks

configs/README.md, configs/alcf/20190405.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta.yrs41-50.conf, configs/alcf/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl, configs/cori/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix, configs/cori/config.20180511.GMPAS-IAF.T62_oEC60to30v3wLI.edison, configs/cori/config.20180514.G.oQU240wLI.edison, configs/cori/config.20190225.GMPAS-DIB-IAF-ISMF.T62_oEC60to30v3wLI.cori-knl, configs/cori/job_script.cori-haswell.bash, configs/cori/job_script.cori-knl.bash, configs/polarRegions.conf, mpas_analysis/config.default
This file `configs/polarRegions.conf` contains new "defaults" for E3SM cryosphere runs that should override the defaults in `mpas_analysis/config.default`
Also updates values in `config.default` for colormap indices and colorbar ranges for the MOC, Hovmoller temperature and salinity anomaly, and Argo bias plots.
Example usage (see `configs/README.md`):
```
python -m mpas_analysis configs/polarRegions.conf my_favorite.conf --generate=climatologyMapSSH --purge
```
If using the conda package, you'll need to download https://raw.githubusercontent.com/MPAS-Dev/MPAS-Analysis/develop/configs/polarRegions.conf and then run something like:
```
mpas_analysis polarRegions.conf my_favorite.conf --generate=climatologyMapSSH --purge
```
=> Add a cryosphere default config file

ci/requirements.yml
It must have come through another package up to now.
=> Add basemap to Travis CI

README.md, docs/versions.rst
I finally got the docs working at https://mpas-dev.github.io/MPAS-Analysis/ so this PR points to the new docs there.
closes #652
=> Point to GitHub Pages version of the docs

configs/polarRegions.conf, docs/config/climatology.rst, docs/config/dask_threads.rst, docs/configuration.rst, docs/tasks/regionalTSDiagrams.rst, docs/tasks/timeSeriesAntarcticMelt.rst, docs/tasks/timeSeriesOceanRegions.rst, mpas_analysis/config.default, mpas_analysis/ocean/regional_ts_diagrams.py
Log norm is now the default.  The number of bins for T-S diagrams has also been increased substantially to give more visually pleasing and more detailed diagrams.
Fix a bug in the docs related to dask threads (and not directly related to T-S diagrams, but still...)
Some clean-up of T-S diagram task suggested by pycharm.
=> Add support for log norm for T-S Diagrams

configs/polarRegions.conf, mpas_analysis/ocean/regional_ts_diagrams.py
The log norm raises an error if the limits are set to `None`, so don't set a norm if there aren't any values.
Also, remove some unneeded regions from TS diagrams in the polar regions config.
=> Fix norm for empty TS diagrams

mpas_analysis/shared/climatology/mpas_climatology_task.py
Since multiple tasks may be creating the same symlink, a try/except approach is more robust than checking if the file exists.
=> Change the way for checking if a symlink is needed

mpas_analysis/ocean/regional_ts_diagrams.py
In some configurations of MPAS-Analysis (those on ALCF using xarray/dask to compute climatologies), regional T-S diagrams are attempting to run before the annual climatology they depend on has been computed.
=> Make regionalTSDiagram plots run after climatology

mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/ocean/time_series_ocean_regions.py
We want mask files that can be used on any run, not just the current one so it would be best to create masks for all features, not just the ones requested in the current analysis run.
=> Make masks for all features, not just the requested ones

mpas_analysis/ocean/regional_ts_diagrams.py
The regional T and S depends on masking from the restart file, meaning it cannot be computed for a control run (for which a restart file is not available during main vs. control analysis). This means that it needs to be stored in a file to be read in and plotted, which also should significantly improve efficiency when re-running analysis or performing main vs. control runs.
=> Compute and store regional T, S for T-S diagrams

mpas_analysis/ocean/regional_ts_diagrams.py
Previous file names were too generic -- just the region group, region and season without any mention of what the plot itself was.
=> Fix file names for TS diagrams

docs/conf.py
This should take care of an issue with formatting of numpydoc in the ReadTheDocs sphinx theme
=> Switch from numpydoc to sphinx.ext.napoleon

README.md, mpas_analysis/config.default, mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/shared/io/utility.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py
Region masks including the MOC masks can be created using MPAS-Tools instead of the dask-based python code for increased efficiency. Several tasks have been modified to use the mask creator from MPAS-Tools.
The MOC task has been updated to make its own region masks including the southern transect.  This relies on new functionality exposed in MPAS-Tools 0.0.8 (see https://github.com/MPAS-Dev/MPAS-Tools/pull/292).
Because a geometric_data directory is needed for `geometric_features` data to be cached in, this has been added to the config file.  By default, `geometric_data` goes to a subdirectory of the output base directory but another, more permanent cache directory can be specified for systems with firewalls or where compute nodes don't have internet access.
=> Add support for making MOC basin masks on the fly

mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/containers.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py
Without this fix, tasks are failing because the mask doesn't exist when it is needed.
Testing of this change also made clear that the mask creator tool (`MasMaskCreator.x`) adds
`Regions` to the end of the geojson properties it stores in mask NetCDF variables.  This merge updates the tasks that use these extra properties (`zmin` and `zmax`) to work with this suffix by default.  For backwards compatibility, the old version without the `Regions` suffix is also supported.
A few things are showing up in `pytest` that are deprecated and which I have fixed here:
* import from `containers.abc` instead of `containers`
* switch from `apply` to `map` in `xarray`'s `group_by` feature.
=> Make T-S diagram tasks run after mask tasks

mpas_analysis/ocean/climatology_map_mld.py
`xarray` requires a different syntax for modifying coordinates than was previously allowed.
closes #687
=> Fix MLD climatology map

mpas_analysis/sea_ice/plot_climatology_map_subtask.py
This is a simple one-liner to avoid plotting bias values in sea-ice concentration and thickness maps where no observation is actually there for a bias to make sense.
This is especially relevant for ice thickness, where obs are only available above a certain latitude, and it is therefore misleading to show a bias below that latitude.
=> Mask sea-ice bias points where no observation data is present

ci/test_and_publish_docs.bash
Previously, merges that try to updated the docs fail if there were no changes (trying to push an empty commit).  With this change, the docs will simply not get updated if there are no changes.
=> Make docs not fail if no change

configs/polarRegions.conf, mpas_analysis/config.default, mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/ocean/plot_hovmoller_subtask.py, mpas_analysis/ocean/plot_transect_subtask.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/shared/plot/time_series.py, mpas_analysis/shared/plot/vertical_section.py
This merge fixes moving averaging in Hovmoller plots.
It also adds support for main vs. control Hovmoller plots.
In the process of adding main vs. control support, some clean-up was performed:
* adding support for suffixes other than `Result` and `Difference` in color maps for vertical section plots (a feature I didn't end up using)
* some PEP8 and other formatting clean-up suggested by pycharm
This merge also updates the ocean regional profiles for "polar regions" configurations.  It switches to the Antarctic regions by default, focuses on the top 600 m, not the full depth of the ocean, and turns on Hovmoller plots as well as profile plots.
=> Updates to Hovmoller plots

configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl, configs/cori/config.20180129.DECKv1b_piControl.ne30_oEC.edison, configs/cori/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix, configs/cori/config.20180511.GMPAS-IAF.T62_oEC60to30v3wLI.edison, configs/cori/config.20180514.G.oQU240wLI.edison, configs/cori/config.20190225.GMPAS-DIB-IAF-ISMF.T62_oEC60to30v3wLI.cori-knl, configs/cori/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/cori/job_script.cori-haswell.bash, configs/cori/job_script.cori-knl.bash, configs/plots/config.drake_contours
Updated all config and job_script templates for cori, changing `acme` to `e3sm`.
=> Change from 'acme' to 'e3sm' for NERSC template files

mpas_analysis/obs/analysis_input_files, mpas_analysis/ocean/regional_ts_diagrams.py, preprocess_observations/preprocess_T_S_climatology.py
This merge adds a preprocessing script for the time-consuming step of making seasonal climatologies of SOSE and WOA18 observations.  Climatologies for ANN, JFM and JAS are now included in the observations to download (and are available on LANL IC, anvil and cori so far).
Reading the cached observations will also hopefully prevent some i/o related hanging that we have seen recently.
=> Use cached T/S obs. climos (when available) in T/S diagrams

mpas_analysis/shared/climatology/mpas_climatology_task.py
We never use `stdin` to specify files to process, but `ncclimo` gets confused when running via `pytest` (which uses `stdin` for other purposes) so we need to explicitly disable `stdin`.
=> Disable ncclimo files from stdin

mpas_analysis/shared/timekeeping/utility.py
This should hopefully improve problems with string decoding
closes #704
=> Switch simulationStartTime to xarray

mpas_analysis/ocean/remap_depth_slices_subtask.py
The modification used the `xarray`, rather than the `numpy`, version of `argmin`, which is better because it refers to the named dimension rather than the axis number.
=> Fix an issue with argmin with newest xarray

configs/acme1/config.20180129.DECKv1b_piControl.ne30_oEC.edison, configs/alcf/20190405.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta.yrs41-50.conf, configs/alcf/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta, configs/alcf/config.20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta, configs/anvil/config.SO60to10ISC.20200108, configs/compy/config.20190711.testLuke.A_WCYCL1850S.ne30_oECv3.compy, configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl, configs/cori/config.20180129.DECKv1b_piControl.ne30_oEC.edison, configs/cori/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix, configs/cori/config.20180511.GMPAS-IAF.T62_oEC60to30v3wLI.edison, configs/cori/config.20180514.G.oQU240wLI.edison, configs/cori/config.20190225.GMPAS-DIB-IAF-ISMF.T62_oEC60to30v3wLI.cori-knl, configs/cori/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/lanl/config.BGCphaeo4.testrun, configs/lanl/config.CONUS.100km.NAEC60to30cr8.20181218, configs/lanl/config.GMPAS-OECO-ODMS-IAF.oRRS30to10v3, configs/lanl/config.MatchBoth_orig, configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison, configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan, configs/polarRegions.conf, docs/config/index.rst, docs/config/input.rst, docs/config/timeSeries.rst, mpas_analysis/config.default, mpas_analysis/shared/analysis_task.py, mpas_analysis/test/test_mpas_climatology_task/config.QU240, mpas_analysis/test/test_remap_obs_clim_subtask/config.remap_obs
For polar regions runs, this is now the default.
`endYear` may now be set to `end` instead of 9999 to indicate the end of the data, and is valid even when `errorOnMissing = True`.
The example config files have been updated with `end` instead of `9999` and with a new comment.
The documentation has also been updated with the changes.
=> Optionally, raise an error if requested input files are missing

docs/api.rst, mpas_analysis/configuration/mpas_analysis_config_parser.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/time_series/time_series.py
In a few cases, lists of items were being referenced inside of a string literal, which seems to cause trouble since sphinx/napoleon are also trying to turn them into a string literal.
There is no reason to generate documentation for the `MpasAnalysisConfigParser` class, since the constructor and most methods are inherited from `ConfigParser`.
=> Update docstrings to get rid of recent warnings

config.example, docs/index.rst, docs/tutorials.rst, docs/tutorials/getting_started.rst, mpas_analysis/config.default
This tutorial will also be recorded as a video for the E3SM web site.
This merge also updates the example config file.  This is partly to sync it better with config.defaults, partly to delete some outdated config options, and partly to improve the comments.
=> Add a tutorial for running analysis on a QU480 run

mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/ocean/time_series_transport.py
Since no valid run is specified, "end" does not get replaced with a valid last year of data, resulting in an error instead of listing the analysis tasks.
=> Fix --list flag

mpas_analysis/shared/plot/colormap.py
Accessing the colormap dictionary is not considered good practice, so switching to the `colormaps()` function.
=> Fix how colormaps are plotted

docs/config/execute.rst, mpas_analysis/config.default, mpas_analysis/shared/climatology/mpas_climatology_task.py
This has been supported in `ncclimo` for awhile but not in MPAS-Analysis.  It is highly desirable on machines where 12 threads are too many for larger meshes on one node, but where running on multiple nodes just for `ncclimo` is kind of a pain.
closes #559
=> Add support for fewer than 12 ncclimo threads

mpas_analysis/ocean/climatology_map_antarctic_melt.py
Needs to run after climatologies have been computed.
=> Fix race condition with melt tables

README.md, ci/recipe/meta.yaml, mpas_analysis/config.default, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/io/utility.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py, mpas_analysis/shared/transects/compute_transect_masks_subtask.py
This was causing problems for systems where /tmp fills up.
This requires changes in `mpas_tools>=0.0.13`.
closes #729
=> Use output directories for temp files/dirs

docs/tutorials/getting_started.rst
This flag is needed on lots of systems and seems to do no harm on those where it isn't required.
Partially addresses #731
=> Update tutorial to include HDF5_USE_FILE_LOCKING=FALSE

docs/tutorials/getting_started.rst, mpas_analysis/__init__.py, mpas_analysis/__main__.py, mpas_analysis/config.default, mpas_analysis/ocean/climatology_map_argo.py, mpas_analysis/ocean/climatology_map_bgc.py, mpas_analysis/ocean/climatology_map_eke.py, mpas_analysis/ocean/climatology_map_ohc_anomaly.py, mpas_analysis/ocean/climatology_map_ssh.py, mpas_analysis/ocean/climatology_map_woa.py, mpas_analysis/ocean/compute_transects_subtask.py, mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py, mpas_analysis/ocean/remap_depth_slices_subtask.py, mpas_analysis/ocean/remap_sose_climatology.py, mpas_analysis/ocean/sose_transects.py, mpas_analysis/shared/analysis_task.py, mpas_analysis/shared/climatology/ref_year_mpas_climatology_task.py, mpas_analysis/shared/interpolation/interp_1d.py, mpas_analysis/shared/io/download.py, mpas_analysis/shared/plot/climatology_map.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py, mpas_analysis/shared/timekeeping/utility.py
Python seems to have switched to a new level of deprecation and unclosed file warnings (possibly https://www.python.org/dev/peps/pep-0565/) and this revealed a number of small issues that are fixed here:
* log files were not being closed
* various deprecated methods and function arguments
* some unused imports
I also noticed an error in the formatting of the tutorial that has been fixed.
=> A large number fixes revealed by new deprecation warnings

mpas_analysis/shared/regions/compute_region_masks.py
It does not need to block all tasks because it isn't running in parallel.
=> Use only one subprocess for MPAS-Tools mask creator

mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/time_series_ocean_regions.py
The mask and time series need to be loaded before masking in both ocean regional time series and T-S diagrams. Otherwise, regions with no cells cause NetCDF problems in xarray 0.16.1
=> Fix masking of ocean regions

configs/anvil/20201024.GMPAS-IAF.T62_oQU240wLIC.anvil.cfg, configs/anvil/20201025.GMPAS-IAF.T62_oQU240wLI.anvil.cfg, configs/anvil/job_script.anvil.bash, configs/anvil/test_suite/QU480.cfg, configs/anvil/test_suite/ctrl.cfg, configs/anvil/test_suite/job_script.bash, configs/anvil/test_suite/job_script_no_polar_regions.bash, configs/anvil/test_suite/main.cfg, configs/anvil/test_suite/main_vs_ctrl.cfg, configs/anvil/test_suite/no_ncclimo.cfg, configs/anvil/test_suite/test_suite.bash
The test suite tests the following, mostly with a QU240wLI simulation that I just ran off of E3SM master today:
* main with python 3.7
* main with python 3.8
* main vs. ctrl
* no ncclimo
* no polar regions
* setup only
* html only
* list
* colormaps
* main with the xarray master branch (to get advanced warning about potential incompatibilities)
* a QU480 run
I also updated the Anvil example run and job script to point to the "main" QU240wLI run.
=> Add a test suite for MPAS-Analysis on Anvil

mpas_analysis/ocean/time_series_antarctic_melt.py
Melt time series are taking long enough to compute, particularly for long time series, that it is necessary to break them into separate subtasks that write out files at yearly intervals, as is done for other time-consuming time-series tasks.
=> Break Antarctic melt time series into subtasks per year

mpas_analysis/config.default, mpas_analysis/ocean/regional_ts_diagrams.py
This merge includes:
* Changing axis labels and default colormap for T-S diagrams.  There is now a single x and y axis label for all panels.  The color map no longer fades to white at low density.
* Coarsening the bins for the T/S diagrams. Otherwise, they are not dense enough to be well sampled at lower resolution.
* Adding support for user-specified min/max vol in TS diagrams
=> Various updates to T-S diagrams

.gitignore, configs/anvil/test_suite/QU480.cfg, configs/anvil/test_suite/clean_suilte.bash, configs/anvil/test_suite/ctrl.cfg, configs/anvil/test_suite/job_script.bash, configs/anvil/test_suite/job_script_no_polar_regions.bash, configs/anvil/test_suite/main.cfg, configs/anvil/test_suite/main_vs_ctrl.cfg, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/shared/climatology/mpas_climatology_task.py
The test suite on Anvil has been failing without me having noticed.  This PR fixes many small issues so it's working:
* Remove melt-rates from QU480 test case, since it doesn't include ice-shelf cavities
* Add missing `makedirs` call in ocean regional time series
* Adds an explicit `endYear = 8` to time series to main vs. ctrl analysis works correctly
* Fixes the name of the stream for min/max streams (was using the "average" stream name for all streams, which isn't correct).
* Add the `--verbose` flag to Anvil test suite so we can see why setup fails if it does.
This merge also includes a few clean-up changes:
* Add a clean-up script to the test suite -- deletes the analysis, html and test-suite logs file output so everything can start fresh
* Add the `anvil_test_suite` directory to the …
=> Fix anvil testsuite

configs/polarRegions.conf
This helps to show more of the important detail, particularly for lower melt rates.
=> Reduce the range for melt-rate plots to +/- 20 m/yr

mpas_analysis/ocean/time_series_antarctic_melt.py
These measurements were originally missing because they are not in the Rignot et al. (2013) table.
The uncertainties for Filchner-Ronne and Ross have been computed simply by adding the uncertainties of the two constituent pieces of each shelf.  This is likely an overestimate but seems the safest option for our visualization purpose, since we do not have enough information to combine them in another way (e.g. RMS weighted by the number of measurements used to obtain each).
=> Add Rignot obs for Antarctic, FRIS, Ross

mpas_analysis/ocean/ocean_regional_profiles.py
It is defaulting to the upper right in some cases, and therefore getting covered by the inset:
=> Move the legend to the lower left for regional profiles

mpas_analysis/config.default, mpas_analysis/ocean/plot_climatology_map_subtask.py, mpas_analysis/shared/plot/climatology_map.py
The user can optionally switch back to the old behavior of using the MPAS coastline.
Lat/lon contours have been added (partly to cover up a seam in the coastline geometry).
The default color for continents is now the lighter gray used for polar projections, and this also applies to global plots.
=> Use cartopy coastline by default in  polar projection plots

README.md, ci/recipe/meta.yaml, configs/polarRegions.conf, mpas_analysis/config.default, mpas_analysis/ocean/climatology_map_antarctic_melt.py, mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/ocean/time_series_transport.py, mpas_analysis/shared/regions/__init__.py, mpas_analysis/shared/regions/compute_region_masks.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py, mpas_analysis/shared/transects/__init__.py, mpas_analysis/shared/transects/compute_transect_masks_subtask.py
This merge makes it easier to add new region masks to MPAS-Analysis by defining a dictionary to define a new mask.  The mask is defined by:
* a region (or transect) group name
* a prefix (so far, just a mangling of the region name: `Antarctic Regions` --> `antarcticRegions`)
* a date (today's date if adding or updating a cached mask file)
* a function for creating the feature collection with the regions for each mask, which should come from `geometric_features.aggregation`
If a mask file for the MPAS mesh already exists, it will be used.  If not and if a geojson file already exists in the `diagnostics` or `customDiagnostics` directory tree with the name `<prefix><date>.geojson`, it will be used to create the mask file.  If neither exists, the function from `geometric_features.aggregation` …
=> Build region and transect masks from geometric_features aggregation

configs/polarRegions.conf, mpas_analysis/__main__.py, mpas_analysis/config.default, mpas_analysis/ocean/__init__.py, mpas_analysis/ocean/hovmoller_ocean_regions.py, mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/ocean/plot_hovmoller_subtask.py, mpas_analysis/shared/plot/vertical_section.py, mpas_analysis/shared/time_series/anomaly.py
The new `hovmollerOceanRegions` task also supports anomalies relative to the first year of the time series with `computeAnomaly = True` in the configuration section for the region group.  For this to be useful, the user will probably need to change the ranges of the color maps.
Also, this merge makes the `oceanRegionalProfiles` task support multiple region groups.  This capability is still a little clumsy and could be improved further in the future.  Each field only has one section in the config file, meaning the user can't currently set different temperature ranges for different region groups.
To support both of these changes, the `oceanRegionalProfiles` task now has a functionality for adding a new range of years and/or region group (creating all of the subtasks to compute the …
=> Break hovmollerOceanRegions into its own task

README.md, ci/recipe/meta.yaml, mpas_analysis/shared/regions/compute_region_masks_subtask.py
This merge adds `Arctic Ocean Regions` and `Arctic Sea Ice Regions` as new region groups that can be used to perform regional analysis.  It requires the latest changes from `geometric_features` (https://github.com/MPAS-Dev/geometric_features/pull/158).
closes #712
=> Add region groups for Arctic ocean and sea-ice regions

docs/tasks/timeSeriesOHCAnomaly.rst, mpas_analysis/__main__.py, mpas_analysis/config.default, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/shared/plot/climatology_map.py, mpas_analysis/shared/plot/oned.py, mpas_analysis/shared/plot/time_series.py, mpas_analysis/shared/plot/title.py, mpas_analysis/shared/plot/vertical_section.py
This should prevent very long run names from changing the sizes of figures.
Some default font sizes were also reduced and figure sizes adjusted to allow for longer panel titles and better relative font size between titles and axes.
closes #765
=> Add capability to limit the lengths of plot titles

ci/recipe/meta.yaml, docs/versions.rst, mpas_analysis/__init__.py, setup.py
In anticipation of the next release.
From now on, versioning will follow the conventions of [semantic versioning](https://semver.org/), reserving the last digit of versions for patches, rather than minor revisions.
=> Update to version 1.3.0

docs/config/regions.rst, docs/tasks/climatologyMapAntarcticMelt.rst, docs/tasks/regionalTSDiagrams.rst, docs/tasks/timeSeriesOceanRegions.rst, docs/tasks/timeSeriesTransport.rst
Some of the documentation was not fully updated following the recent move to using feature aggregation from geometric_features, rather than caching geojson files without provenance.
A few other updates to the documentation have also been made as needed corrections were discovered along the way.
=> Update documentation related to region groups

mpas_analysis/config.default
This adds a 0 contour in the Global plot of the MOC streamfunction in `config.default`.
It also adds the computation of the `IndoPacific` MOC by default.
=> Added 0 contour in MOC global

ci/recipe/meta.yaml, docs/api.rst, docs/config/regions.rst, docs/tasks/hovmollerOceanRegions.rst, docs/tasks/oceanRegionalProfiles.rst, mpas_analysis/shared/regions/__init__.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py, mpas_analysis/shared/transects/__init__.py, mpas_analysis/shared/transects/compute_transect_masks_subtask.py
This will allow the same process to be used in MPAS-Analysis and compass for creating region masks, meaning the correct region masks for MPAS-Analysis can be generated along with new meshes in compass.
=> Switch to using geometric_features aggregation lookup

mpas_analysis/config.default, mpas_analysis/ocean/time_series_transport.py
The optimizations include precomputing transect indices and load time series data files before extracting specific transects and computing on them, rather trying to extract transects and then load only that data.
=> Improve performance of  timeSeriesTransport task

README.md, ci/recipe/meta.yaml, docs/conf.py, docs/config/execute.rst, mpas_analysis/config.default, mpas_analysis/shared/regions/compute_region_masks.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py, mpas_analysis/shared/transects/compute_transect_masks_subtask.py, setup.py
Simulations with large meshes and without cached region masks have been hanging.  This PR is expected to make mask creation reliable and efficient for large meshes.
All region mask creation is with the command-line tools.  Transport transects are still done with `mpas_tools.mesh.conversion.mask` (which uses the `MpasMaskCreator.x` c++ tool) because the `edgeSign` variable produced by this approach is needed, and the python tool for creating transect masks doesn't yet produce `edgeSign`.
A new config option is added, `[execute]/multiprocessingMethod`, which specifies which python multiprocessing method (`spawn`, `fork` or `forkserver`) is used.  For now, `spawn` seems to work well on all machines.  `fork` and `forkserver` were found to not work well on Anvil with python 3.7 (but were fine …
=> Switch to MPAS-Tools python command-line tools for region mask creation

mpas_analysis/shared/html/image_xml.py, mpas_analysis/shared/html/pages.py, mpas_analysis/shared/io/utility.py
This is needed on Chrysalis, where PNG file copies are occasionally failing with:
```
BlockingIOError: [Errno 11] Resource temporarily unavailable
```
=> Fallback to slow file copy on exception

configs/compy/test_suite/job_script.bash, configs/compy/test_suite/job_script_no_polar_regions.bash, configs/compy/test_suite/test_suite.bash, configs/cori/test_suite/job_script.bash, configs/cori/test_suite/job_script_no_polar_regions.bash, configs/cori/test_suite/test_suite.bash, configs/lcrc/test_suite/anvil/job_script.bash, configs/lcrc/test_suite/anvil/job_script_no_polar_regions.bash, configs/lcrc/test_suite/chrysalis/job_script.bash, configs/lcrc/test_suite/chrysalis/job_script_no_polar_regions.bash, configs/lcrc/test_suite/test_suite.bash
Make sure jobs stop on errors.  Previously, the webpages were being generated even when there were errors, which wasn't usually helpful.
Use `srun` calls and `python -m` consistently throughout.
Update suites to py 3.8 and 3.9
Build 3.9 envs before 3.8
Run 3.9 job before others (because of `main_vs_ctrl` job dependency that takes the longest)
=> Various fixes and updates to test suites

mpas_analysis/config.default, mpas_analysis/ocean/streamfunction_moc.py
This merge fixes two issues with indexing regions in the  MOC.
First, the offline MOC calculation was previously assuming the requested regions from the config file were in the same order as the regions in the region masks file.  This is obviously not necessarily the case.  We happen to request the Atlantic and IndoPacific by default (indices 0 and 1) but if we asked for the pacific region, the code before this merge would plot the IndoPacific and call it the Pacific.
Second, the online MOC calculation was always plotting index 0 (the Atlantic) for each region before this fix.
The fix is to read in the regions from the mask file and compute indices for each, then, to use the names of the requested region to look up the correct indices.
closes #789
=> Fix indexing issues with the MOC

utility_scripts/make_ismip6_region_masks.py
This requires `geometric_features >= 0.2.0` and `mpas_tools >= 0.5.0`.
These regions were used in [Barthel et al. (2020)](https://doi.org/10.5194/tc-14-855-2020) and will be used in a paper we're working on, too.
=> Add utility script for making ISMIP6 obs region masks

mpas_analysis/ocean/time_series_transport.py, mpas_analysis/shared/plot/colormap.py, mpas_analysis/shared/transects/compute_transect_masks_subtask.py
Now that edge signs are available in python transect masks, we should use these instead.  They are more accurate and should be more efficient to compute for big meshes.
Since the python mask creator doesn't produce a series of edge indices, the computation of the transport has been updated to use the edge masks instead.
A large number of warnings appeared in some log files related to trying to re-add color maps.  A fix to remove these warnings is included here for convenience.
=> Switch to python transect masks

mpas_analysis/config.default, mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/ocean/time_series_sst.py, mpas_analysis/ocean/time_series_transport.py, mpas_analysis/sea_ice/time_series.py, mpas_analysis/shared/plot/time_series.py
Rather than hard-coding the main time series to be red, the control to be black, etc. these are now config options.
=> Select time-series colors from config options

mpas_analysis/ocean/time_series_ocean_regions.py
The attribute `is3d` should now be retained by `xarray` for later use in plotting.
=> Fix missing is3d attribute

mpas_analysis/ocean/time_series_antarctic_melt.py
This seems to overlap with plots less frequently.
This merge also adds the ability to specify the tick locations on the time axis.
=> Move `timeSeriesAntarcticMelt` legends to upper left

README.md
It wasn't clear to some developers that you need to be in the base of the cloned repo for the instructions to work.  Hopefully, this change clears that up.
=> Update readme to clarify dev instructions

ci/recipe/meta.yaml, configs/compy/config.20190711.testLuke.A_WCYCL1850S.ne30_oECv3.compy, configs/compy/job_script.compy.bash, dev-spec.txt, mpas_analysis/config.default, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py, mpas_analysis/test/test_mpas_climatology_task/config.QU240, mpas_analysis/test/test_remap_obs_clim_subtask/config.remap_obs
This is needed on compy (and possibly other places) to handle ESMF built with system MPI.
Update compy examples for new system ESMF support.
Update to 1.4.0rc3
=>  Add ncremap parallel exec 

ci/recipe/meta.yaml, dev-spec.txt, mpas_analysis/config.default
This merge also adds the `AtlanticMed` region to default MOC basins.
It adds config options for the Indian and Pacific MOC basins in case users want to plot those, though they are not plotted by default.
This requires a release of geometric_features after https://github.com/MPAS-Dev/geometric_features/pull/176 has been merged.
=> Update `geometric_features` version for new MOC basins

config.example, configs/alcf/job_script.cooley.18to6.bash, configs/alcf/job_script.cooley.30to10.bash, configs/compy/job_script.compy.bash, configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl, configs/cori/config.20180129.DECKv1b_piControl.ne30_oEC.edison, configs/cori/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix, configs/cori/config.20180511.GMPAS-IAF.T62_oEC60to30v3wLI.edison, configs/cori/config.20180514.G.oQU240wLI.edison, configs/cori/config.20190225.GMPAS-DIB-IAF-ISMF.T62_oEC60to30v3wLI.cori-knl, configs/cori/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison, configs/cori/job_script.cori-haswell.bash, configs/cori/job_script.cori-knl.bash, configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf, configs/lanl/config.BGCphaeo4.testrun, configs/lanl/config.CONUS.100km.NAEC60to30cr8.20181218, configs/lanl/config.GMPAS-OECO-ODMS-IAF.oRRS30to10v3, configs/lanl/config.MatchBoth_orig, configs/lanl/job_script.lanl.bash, configs/lcrc/20201025.GMPAS-IAF.T62_oQU240wLI.anvil.cfg, configs/lcrc/job_script.anvil.bash, configs/lcrc/job_script.chrysalis.bash, configs/olcf/job_script.olcf.bash, docs/config/execute.rst
The example job scripts now refer to the location where E3SM-Unified 1.5.0 will be installed on each supported machine.  The config options include those needed to support system MPI (on machines where that is part of E3SM-Unified) on compute nodes. These are the parallel executables that are prefixes to the command line for generating mapping files and for calling ncremap (either `srun` or the default `None`, depending on the machine).
The documentation has also been updated to describe the parallel prefixes.
=> Update docs and example configs for E3SM-Unified 1.5.0

mpas_analysis/ocean/climatology_map_bgc.py
The name of the field was `timeMonthly_avg_ecosysTracers_Chl` instead of simply `Chl`.
closes #825
=> Fix the name of the chlorophyll field for comparison

docs/api.rst, docs/config/transects.rst, mpas_analysis/default.cfg, mpas_analysis/ocean/climatology_map_ohc_anomaly.py, mpas_analysis/ocean/compute_transects_subtask.py, mpas_analysis/ocean/geojson_transects.py, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/ocean/plot_hovmoller_subtask.py, mpas_analysis/ocean/plot_transect_subtask.py, mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/remap_depth_slices_subtask.py, mpas_analysis/ocean/sose_transects.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/ocean/utility.py, mpas_analysis/ocean/woce_transects.py, mpas_analysis/polar_regions.cfg, mpas_analysis/shared/climatology/__init__.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py, mpas_analysis/shared/plot/inset.py, mpas_analysis/shared/plot/vertical_section.py
This merge adds support for using MPAS-Tools to compute transects on the native MPAS-Ocean mesh.  Observations are interpolated to the MPAS transect so comparison can also take place on this mesh.
Major changes are made to how vertical sections are plotted, making a `matplotlib.tri.Triangulation` from the logically rectangular grids we have used so far so that we can optionally pass the arguments needed to create a triangulation on the native MPAS mesh.  The approach of outlining the valid region of the transect using a contour also no longer works with the native triangulation, so coordinates for producing an outline can optionally be passed in instead.
The `mpas` native grid has been made the default in `configs/polarRegions.conf`.
closes #586
=> Add support for transects plotted on the native MPAS-Ocean mesh

azure-pipelines.yml, ci/python3.10.yaml, ci/recipe/meta.yaml, dev-spec.txt
This merge also removes python 3.7 from testing and makes python 3.9 the version for creating documentation and testing xarray's master branch
=> Add python 3.10 support and testing

mpas_analysis/ocean/plot_transect_subtask.py, mpas_analysis/shared/plot/vertical_section.py
After some discussion below, the most straightforward solution seems to be to remove the line between the topography and the colormap, and make the `NaN` color the same as the background color.
closes #849
=> Improve model vs. obs transects on the native MPAS mesh

mpas_analysis/shared/html/pages.py
If analysis is on a known machine with a web portal, print the URL where the analysis can be found at the end of the run.
closes #841
=> Print the URL for the web page

suite/job_script.bash, suite/setup.py
Before this fix, each test's directory was given appropriate world read/execute permissions but the common directory that all tests reside in was not necessarily world readable.
=> `chmod` common HTML directory in test suite

ci/recipe/meta.yaml, dev-spec.txt, mpas_analysis/shared/plot/climatology_map.py
What should be fill values were coming through as zeros.  A temporary fix is to use `validMask` to assign fill values.
closes #860
=> Fix masking of surface climatologies

mpas_analysis/configuration/anvil.cfg
This is needed because of out-of-memory errors that have been seen in some recent runs.
closes #864
=> Reduce ncclimo tasks for Anvil to 6

suite/run_suite.bash
On Anvil, the test suite has been leaving behind main vs. control jobs when the main job fails.  With a flag (`--kill-on-ivalid-dep=yes`), this shouldn't happen anymore.
=> Update test suite to kill jobs with invalid deps

ci/recipe/meta.yaml, dev-spec.txt, mpas_analysis/shared/io/namelist_streams_interface.py, mpas_analysis/test/test_namelist_streams_interface/namelist.ocean
This is a more robust and general tool than what we have.
closes #871
=> Switch to using `f90nml` for reading namelists

mpas_analysis/default.cfg, mpas_analysis/ocean/plot_transect_subtask.py, mpas_analysis/ocean/sose_transects.py, mpas_analysis/ocean/woce_transects.py, mpas_analysis/polar_regions.cfg, mpas_analysis/shared/plot/colormap.py, mpas_analysis/shared/plot/vertical_section.py
A request was made by the cryosphere team for density contour plots that can be compared either with observations (or SOSE) or against other model runs.  The aim with these plots is to compare the slopes of isopicnals as we vary eddy parameterizations (GM and Redi).
This merge adds galleries of density contour plots on WOCE and SOSE transects.  Here are two WOCE examples:
This merge also fixes several issues that emerged in contour comparison plots.  We have not tried them since moving to plotting transects with triangles on the native MPAS grid.  Some problems emerged, most notably that contours on triangles do not seem to allow value labels on the contours themselves.
As an alternative to contour labels, plots with color maps have been used instead.  The color maps were chosen to try to …
=> Add WOCE and SOSE density contour plots

mpas_analysis/ocean/time_series_antarctic_melt.py
This was erroneously removed in https://github.com/MPAS-Dev/MPAS-Analysis/pull/806, probably because it was useful for some one-off analysis for publication figures.
=> Add back legend for Antarctic melt flux time series

suite/job_script.bash, suite/run_e3sm_unified_suite.bash, suite/setup.py, suite/template.cfg
This merge adds a bash script for testing E3SM-Unified.  Various changes to the setup script and templates were needed to make this work.
=> Add E3SM-Unified support to test suite

mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/time_series_ocean_regions.py
It appears a recent change in xarray or dask has broken the way MPAS-Analysis currently handles region masking on lon/lat grids (i.e. for observations).  A seemingly inconsistent multi-index called `nCells` is generated when going from the 2D lon/lat space to a 1D "unraveled" coordinate.  The easiest way to handle this seems to just be to drop the `nCells` multi-index from both the mask and the data set to be masked.
=> Fix region masking in observations

mpas_analysis/shared/climatology/ref_year_mpas_climatology_task.py
The start and end year for reference climatologies were getting overridden by the user's specified start and end year for normal climatologies.
(This maybe suggests that we should consider a different strategy for setting the start and end years and dates for reference climatologies that doesn't rely on overriding the user config options.)
This fixes issues where the OHC anomaly plots were exactly zero.
closes #883
=> Fix config options for reference-year climatologies 

mpas_analysis/ocean/index_nino34.py, mpas_analysis/sea_ice/time_series.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/generalized_reader/generalized_reader.py, mpas_analysis/shared/io/mpas_reader.py, mpas_analysis/shared/io/namelist_streams_interface.py, mpas_analysis/shared/mpas_xarray/mpas_xarray.py, mpas_analysis/shared/time_series/time_series.py, mpas_analysis/shared/timekeeping/MpasRelativeDelta.py, mpas_analysis/shared/timekeeping/utility.py, mpas_analysis/test/test_climatology.py, mpas_analysis/test/test_generalized_reader.py, mpas_analysis/test/test_mpas_climatology_task/mpas-o_in, mpas_analysis/test/test_mpas_xarray.py, mpas_analysis/test/test_namelist_streams_interface.py, mpas_analysis/test/test_namelist_streams_interface/namelist.ocean, mpas_analysis/test/test_open_mpas_dataset.py, mpas_analysis/test/test_remap_obs_clim_subtask/mpas-o_in, mpas_analysis/test/test_timekeeping.py
For backwards compatibility, namelists withh a `gregorian_noleap` calendar are still supported but `noleap` is used for testing and listed in docstrings.
closes #888
=> Switch to `noleap` instead of `gregorian_noleap`

mpas_analysis/__main__.py
Now, when you give an incorrect machine, e.g.:
```
mpas_analysis -m blah example_e3sm.cfg
```
you get an error message like:
```
Traceback (most recent call last):
File "/home/xylar/code/MPAS-Analysis/improve_error_on_wrong_machine/mpas_analysis/__main__.py", line 799, in main
config.add_from_package('mache.machines', f'{machine}.cfg')
File "/home/xylar/mambaforge/envs/mpas_dev/lib/python3.10/site-packages/mpas_tools/config.py", line 87, in add_from_package
self._add(path, user=False)
File "/home/xylar/mambaforge/envs/mpas_dev/lib/python3.10/site-packages/mpas_tools/config.py", line 426, in _add
raise FileNotFoundError(f'Config file does not exist: {filename}')
FileNotFoundError: Config file does not exist: /home/xylar/mambaforge/envs/mpas_dev/lib/python3.10/site-packages/mache/machines/bl …
```
=> Improve error message on incorrect machine

mpas_analysis/ocean/climatology_map_ohc_anomaly.py
In order to be a reference analysis task for the tutorial, ``ClimatologyMapOHCAnomaly`` and its subtask
RemapMpasOHCClimatology have been cleaned up to:
* follow the PEP8 style guide
* fix docstrings
* use f-strings instead of format calls
* simplify ``super()`` calls
* keep lines under 79 characters where sensible
=> Clean up ``ClimatologyMapOHCAnomaly``

mpas_analysis/ocean/streamfunction_moc.py
To match changes made in E3SM in https://github.com/E3SM-Project/E3SM/pull/5170, this merge changes the transport computation into the southern boundary of an MOC region to work from the bottom up rather than the top down.
This merge also adds the submesoscale velocity to the postprocessed MOC computation.
Finally, we also add the full AMOC to the time-series output for debugging and follow-up analysis.  No plots are made of these fields.
=> Update postprocessed MOC to match analysis member

mpas_analysis/ocean/streamfunction_moc.py
I think I forgot to run the test suite on #886 and thus missed this issue.
=> Add missing var when continuing MOC calculation

ci/recipe/meta.yaml, dev-spec.txt, suite/job_script.bash, suite/setup.py
We build the package on HPC using the CI recipe, so it is better if it doesn't use conda's MPI.  In addition, we don't want development environments to include MPI because the conda MPI package typically don't work on HPC, where we do a lot of our development and testing.
Finally, this merge also removes some unnecessary `srun` calls to `mpas_analysis` in the test suite.  On many systems, nesting calls to `srun` within a parallel job doesn't work, and given that we may want to call `ESMF_RegridWeightGen` or `ncclimo` with `srun` within MPAS-Analysis, it would be better if we don't also call `mpas_analysis` unnecessarily with `srun`.
=> Make sure both CI and develoment environments don't include conda MPI

mpas_analysis/ocean/plot_hovmoller_subtask.py
Sometimes, runs have slightly different Time values in timeSeriesStatsMonthly (seemingly related to restarts). When this happens, the hovmoller differences are only at times that match exactly, leading to a diff field with the wrong size.
This merge fixes the issue by first checking to make sure the two runs start and end at (approximately) the same time, then using the time from the "main" run for the "reference" run, too.
=> Fix hovmoller plot comparison

mpas_analysis/__main__.py
It needs to take precidence over the config option but wasn't doing so because the "user" config option was taking priority.
=> Fix generate command-line flag

mpas_analysis/ocean/compute_transects_subtask.py
xarray seems to have trouble with masking a dataset with a `cftime._cftime.DatetimeNoLeap` time coordinated.  To avoid this, we'll just not decode time since we don't need to.
=> Don't decode time as part of transect remapping

mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/time_series_ocean_regions.py
This happens when we're trying to expand the "all" region name but doing so during `mpas_analysis --list`, so that we don't have a valid output directory.
=> Fix `--list` when trying to write geojson files

mpas_analysis/__main__.py, mpas_analysis/shared/analysis_task.py
This happens frequently by mistake and produces a very obscure error message.  With this merge, the error message will be more straightforward, e.g.:
```
ValueError: Analysis tasks failed these checks:
A task named climatologyMapSeaIceSpeedSH has been added more than once
```
=> Add a check for duplicate analysis tasks and subtasks

mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
This merge adds support for remapping from MPAS variables at vertices to comparison grids.
To make sure mapping files are unique, `_vertices` is appended to the name of the MPAS mesh if it maps from vertices instead of cells.  We will eventually want to cache these new mapping files just like we do for the cell versions and compute them in compass with new meshes along with the existing mapping files.
To remap variables on vertices, you need to create a `RemapMpasClimatologySubtask` object with `vertices=True` as a parameter.
=> Add support for remapping from MPAS vertices

mpas_analysis/__main__.py, mpas_analysis/shared/html/pages.py
The name of the complete config file should now be correct, so that the link works.
The control and main config files are also included if they are supplied.
closes #911
=> Fix config file on the webpage

mpas_analysis/__main__.py, mpas_analysis/default.cfg, mpas_analysis/ocean/__init__.py, mpas_analysis/ocean/climatology_map_bsf.py, mpas_analysis/ocean/plot_climatology_map_subtask.py, mpas_analysis/polar_regions.cfg, mpas_analysis/shared/climatology/comparison_descriptors.py, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py, mpas_analysis/shared/plot/climatology_map.py, mpas_analysis/shared/plot/colormap.py, mpas_analysis/shared/projection/__init__.py
Summary : 
Config option (`climatologyMapBSF`)  for plotting climatological depth integrated transport streamfunction 
- either full depth (Barotropic) or up to a specified depth (task file = `ocean/climatology_map_bsf.py`)
- option to add arrows to contourlines: config option `arrowsOnContour<suffix>`  in `default.cfg`, files updated `shared/plot/climatology_map.py`, `shared/plot/colormap.py`
Subpolar North Atlantic projection to visualize sub polar gyre.
- subpolar North Atlantic projection added to `shared/projection/__init__.py`, `shared/climatology/comparison_descriptors.py` and `shared/climatology/remap_mpas_climatology_subtask.py` 
- doctoring updated in `shared/climatology/comparison_descriptors.py`
=> Add Horizontal Streamfunction plots + Subpolar North Atlantic projection 

mpas_analysis/default.cfg, mpas_analysis/ocean/climatology_map_bsf.py, mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/shared/plot/climatology_map.py
#898 introduced some minor bugs and formatting issues that this merge aims to clean up.
This merge also fixes a slightly complicated issues with xarray.  Previously, we needed to drop an index variable that was introduced by stacking.  That index variable seems to have been introduced inadvertently and is no longer present in the latest xarray.  However, dropping this now nonexistent variable causes problems.  This merge introduces checks so that we only drop that variable if it is present.
=> Fixes to formatting and config options for climatologyMapBSF

docs/developers_guide/api.rst, mpas_analysis/__main__.py, mpas_analysis/default.cfg, mpas_analysis/ocean/climatology_map_antarctic_melt.py, mpas_analysis/ocean/climatology_map_argo.py, mpas_analysis/ocean/climatology_map_bgc.py, mpas_analysis/ocean/climatology_map_bsf.py, mpas_analysis/ocean/climatology_map_eke.py, mpas_analysis/ocean/climatology_map_mld.py, mpas_analysis/ocean/climatology_map_mld_min_max.py, mpas_analysis/ocean/climatology_map_ohc_anomaly.py, mpas_analysis/ocean/climatology_map_schmidtko.py, mpas_analysis/ocean/climatology_map_sose.py, mpas_analysis/ocean/climatology_map_ssh.py, mpas_analysis/ocean/climatology_map_sss.py, mpas_analysis/ocean/climatology_map_sst.py, mpas_analysis/ocean/climatology_map_woa.py, mpas_analysis/ocean/utility.py, mpas_analysis/polar_regions.cfg, mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py, mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py, mpas_analysis/shared/climatology/comparison_descriptors.py, mpas_analysis/shared/plot/__init__.py, mpas_analysis/shared/plot/climatology_map.py, mpas_analysis/shared/plot/oned.py, mpas_analysis/shared/plot/plot_climatology_map_subtask.py, mpas_analysis/shared/plot/time_series.py, mpas_analysis/shared/plot/vertical_section.py, mpas_analysis/shared/projection/__init__.py
This merge moves the class `PlotClimatologyMapSubtask` to the shared infrastructure and generalizes it to handle both ocean and sea-ice climatology plots.
Then, it changes all existing ocean and sea-ice climatology-map tasks to use this shared task.  The version of `PlotClimatologyMapSubtask` in `sea_ice` is retained because sea-ice tasks in development still need to use it.
=> Switch to plotting sea-ice concentration and thickness on projection grids

mpas_analysis/__main__.py, mpas_analysis/default.cfg, mpas_analysis/obs/observational_datasets.xml, mpas_analysis/sea_ice/__init__.py, mpas_analysis/sea_ice/climatology_map_melting.py, mpas_analysis/sea_ice/climatology_map_production.py
Adds analysis task for climatology maps of sea ice total production and freezing, with comparisons to observations based on [Haumann et al 2016](https://www.nature.com/articles/nature19101). Note observations are only available for annual climatology, Southern Hemisphere.
closes #216
=> Add sea ice production/melting analysis tasks

mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py
This merge adds back the `controlConfig` argument to the subtask for plotting sea-ice thickness climatologies so the comparison with a control run gets plotted.
=> Fix comparison of sea-ice thickness vs. control

.gitignore, README.md, docs/users_guide/config/output.rst, docs/users_guide/config/runs.rst, mpas_analysis/__main__.py
This merge also fixes some cases in which example config files are referred to in the old way (`config.*`) instead of the new way (`*.cfg`).
=> Fix complete config file name in log dir

suite/run_e3sm_unified_suite.bash, suite/run_suite.bash
Test python 3.9 and 3.10 (dropping 3.8)
=> Bump python version in test suites

mpas_analysis/shared/climatology/mpas_climatology_task.py
=> Keep attributes in python climatology computations

mpas_analysis/ocean/plot_hovmoller_subtask.py
We want the more restrictive mask (with shallower bathymetry) for comparing Hovmoller plots on different meshes.
=> Fix masking of Hovmoller plots on different meshes

azure-pipelines.yml
We're seeing weird errors in python 3.11 with it:
```
Encountered problems while solving:
- nothing provides __win needed by pysocks-1.7.1-pyh0701188_6
```
=> Disable latest conda in CI (for now)

azure-pipelines.yml
After a new release that should fix the problem with the previous version, we only need to avoid that one version (conda v22.11.0).
=> Loosen constraint on conda

azure-pipelines.yml, dev-spec.txt, mpas_analysis/ocean/time_series_antarctic_melt.py, suite/main_vs_ctrl.cfg, suite/run_suite.bash
This merge also updates `m2r2 >=0.3.3`, which is necessary for python 3.11 to work.
=> Update suite to python 3.11

mpas_analysis/shared/html/pages.py
This was causing errors at the very end of an analysis run on Chicoma.
=> Fix output on machines without web portal

mpas_analysis/ocean/remap_depth_slices_subtask.py, mpas_analysis/shared/plot/vertical_section.py, mpas_analysis/shared/time_series/moving_average.py
Previously, when there were cells with `maxLevelCell = 0`, this caused a failure because there was no valid depth coordinate for that cell and therefore no closest depth index could be found.
This fix simply skips cells that are not in the ocean and masks them out.
This merge also fixes an issue with rolling averages that was discovered in the same run.  Rolling averages should drop `NaN` values only if all values at a given time point are `NaN`, not if *any* are (the default behavior).  This was presumably not noticed previously because we performed rolling averages on fields without any `NaN` values.
=> Fix depth slicing with non-ocean cells

mpas_analysis/ocean/streamfunction_moc.py
Before this merge, we were needlessly computing the MOC basin masks when we use the post-processed MOC calculation, even if the basin masks and transects were already computed.  This change makes sure the mask creation gets skipped when it should.
=> Skip making MOC basin masks if they exist

suite/run_dev_suite.bash, suite/run_e3sm_unified_suite.bash, suite/run_suite.bash, suite/setup.py
This suite runs much faster than the full suite because it uses the `mpas_dev` development environment rather than building conda packages.
This merge also updates test suites to use a new `QU240wLI` run.  This is because I deleted the old one on LCRC by mistake.
This merge also fixes an issue with job dependencies.  (Dependent jobs were not correctly being cancelled when the job they depend on failed.)
=> Add a developer test suite that uses an existing conda env

mpas_analysis/ocean/regional_ts_diagrams.py
With the latest xarray (2023.3.0), we can't use chunked (dask) data arrays as boolean masks anymore.
=> Fix region masking for TS diagrams

mpas_analysis/ocean/streamfunction_moc.py
We need to use `nansum` in some places where a normal sum used to work because of the new masking feature in MPAS-Ocean.
closes #947
=> Fix NaNs in MOC postprocessing

mpas_analysis/ocean/climatology_map_antarctic_melt.py, mpas_analysis/ocean/compute_anomaly_subtask.py, mpas_analysis/ocean/compute_transects_subtask.py, mpas_analysis/ocean/histogram.py, mpas_analysis/ocean/hovmoller_ocean_regions.py, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py, mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/sose_transects.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/ocean/time_series_transport.py, mpas_analysis/sea_ice/time_series.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py, mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py, mpas_analysis/shared/io/__init__.py, mpas_analysis/shared/io/write_netcdf.py, mpas_analysis/shared/regions/compute_region_masks_subtask.py, mpas_analysis/shared/transects/compute_transect_masks_subtask.py, suite/main_vs_ctrl.cfg, suite/moc_am.cfg, suite/run_dev_suite.bash, suite/run_e3sm_unified_suite.bash, suite/run_suite.bash, suite/setup.py
This merge renames `write_netcdf` --> `write_netcdf_with_fill` to avoid confusion with MPAS-Tools, where the `write_netcdf` function also exists and is only for MPAS data.  For clarity, we want the functionality in the MPAS-Analysis version to be more explicit.
The merge aslo switches to using `write_netcdf_with_fill` in most places where `write_netcdf` was previously used.
For more complete testing, I also added a test for the MOC analysis member (the MOC is postprocessed in MPAS-Analysis by default).  It fixes the "main vs. control" run to work properly with the developer and E3SM-Unified suites (where only one version of python is tested), in addition to the default one.
This merge switches to parsing CF when using xarray for MPAS climatologies.  This is necessary to correctly handle …
=> Various fixes to get the `no_ncclimo` test working again

ci/recipe/meta.yaml, dev-spec.txt, mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/time_series_ocean_regions.py
This brings in new definitions of the Weddell and Bellingshausen seas from https://github.com/MPAS-Dev/geometric_features/pull/195
=> Update geometric_features to 1.2.0

README.md, docs/users_guide/tasks/climatologyMapAntarcticMelt.rst, docs/users_guide/tasks/timeSeriesAntarcticMelt.rst, mpas_analysis/docs/parse_quick_start.py, mpas_analysis/obs/observational_datasets.xml, mpas_analysis/ocean/climatology_map_antarctic_melt.py, mpas_analysis/ocean/time_series_antarctic_melt.py, preprocess_observations/preprocess_adusumilli_melt.py
This merge switches climatology maps of Antarctic melt rates to use Adusumilli et al. (2020) instead of Rignot et al. (2013).  It also adds the Adusumilli et al. melt rates and fluxes to the time-series plots as a 3rd observational point (keeping Rignot et al. 2013 present-day and steady-state estimates).
To do:
=> Add Adusumilli et al. (2020) melt rates

mpas_analysis/ocean/climatology_map_antarctic_melt.py
The different rounding used before is leading to unnecessary mapping files being produced.
closes #973
=> Update mesh name for Adusumilli observations

mpas_analysis/shared/plot/climatology_map.py
The area weights (and not just the fields themselves) need to be masked to exclude land.
Before this fix:
Note: mean of 12.36
But this time series of SST:
After the fix:
=> Fix stats for climatology maps

mpas_analysis/shared/html/pages.py
Without them, the NERSC web portal is behaving strangely.
=> Add a trailing slash to printed URLs

ci/recipe/meta.yaml, dev-spec.txt, mpas_analysis/__init__.py
This merge also requires mpas_tools >=0.30.0, which fixes an issue with region masks on lat-lon grids that are needed for SOSE T-S diagrams.
=> Update to v1.9.1

mpas_analysis/default.cfg, mpas_analysis/sea_ice/time_series.py
This prevents out-of-memory issues when computing total area and volume per hemisphere for very long runs.
closes #981
=> Divide sea ice area/volume data into 10 year chunks 

mpas_analysis/shared/plot/climatology_map.py
Contour paths often contain more than one polygon.  We need to add arrows separately to each polygon.
=> Fix arrows in barotropic streamfunction plots

mpas_analysis/ocean/climatology_map_argo.py, mpas_analysis/ocean/climatology_map_mld.py, mpas_analysis/ocean/climatology_map_woa.py, mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/ocean/remap_depth_slices_subtask.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/ocean/time_series_transport.py, mpas_analysis/shared/climatology/climatology.py, mpas_analysis/shared/generalized_reader/generalized_reader.py, mpas_analysis/shared/io/mpas_reader.py, suite/run_dev_suite.bash, suite/run_suite.bash
This should prevent a large number of deprecation warnings that we are getting.
=> Fix dims --> sizes for xarray datasets

mpas_analysis/default.cfg
Before this fix, we were seeing weird colorbars for OHC difference plots, e.g.:
and weird color maps for BSF difference plots, e.g.:
=> Fix colorbars on OHC and BSF difference plots

docs/users_guide/tasks/climatologyMapAntarcticMelt.rst, docs/users_guide/tasks/timeSeriesAntarcticMelt.rst, mpas_analysis/obs/observational_datasets.xml, mpas_analysis/ocean/climatology_map_antarctic_melt.py, mpas_analysis/ocean/time_series_antarctic_melt.py, preprocess_observations/preprocess_paolo_melt.py
This merge switches climatology maps of Antarctic melt rates to use the Paolo et al. (2023) climatology from 1992-2017.  It also adds mean melt rates over that period to the melt-rate time series plots.
A preprocessing script is also included in this merge.  It has been used to generate climatology map and to remap it onto common comparison grids.
The mean melt rates per ice shelf are from Table 3 of the paper.
=> Add Paolo et al. (2023) melt rate analysis

mpas_analysis/ocean/climatology_map_antarctic_melt.py, mpas_analysis/ocean/time_series_antarctic_melt.py
Also plot constituents: the melt rate at the interface and the frazil flux below ice shelves.
This is to support changes in https://github.com/E3SM-Ocean-Discussion/E3SM/pull/79
=> If available, plot climatology of total melt rate

mpas_analysis/ocean/climatology_map_antarctic_melt.py
@irenavankova pointed out in https://github.com/MPAS-Dev/MPAS-Analysis/pull/989#issuecomment-1975020772 that the title is too long and thus produces figures that are slightly shifted depending on the season.
=> Shorten titles of Frazil Accretion Rate plots

docs/tutorials/dev_getting_started.rst, docs/tutorials/getting_started.rst, docs/users_guide/config/index.rst, docs/users_guide/config/timeSeries.rst, mpas_analysis/default.cfg, mpas_analysis/ocean/hovmoller_ocean_regions.py, mpas_analysis/ocean/streamfunction_moc.py, mpas_analysis/ocean/time_series_antarctic_melt.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/ocean/time_series_transport.py, mpas_analysis/polar_regions.cfg, mpas_analysis/shared/analysis_task.py, mpas_analysis/test/test_climatology.py, mpas_analysis/test/test_mpas_climatology_task.py, mpas_analysis/test/test_mpas_climatology_task/QU240.cfg, mpas_analysis/test/test_remap_obs_clim_subtask/remap_obs.cfg
This merge removes the config option `errorOnMissing` from the `[input]` section.  In practice, we always want an error on missing data, rather than simply providing a warning using available data.
This merge also drops support for the `end` value for `endYear`.  For developers, `end` has been more difficult to support than it is worth.  For users, it isn't a great idea to have the same analysis run produce different results depending on how far along a simulation is.  In practice, we always want to run fresh analysis when we want a longer time series.
=> Removed `errorOnMissing` and `endYear = end` config options

mpas_analysis/configuration/chicoma-cpu.cfg, mpas_analysis/configuration/pm-cpu.cfg
This seems to be causing trouble in E3SM-Unified 1.9.3rc2 testing.
=> Don't use `srun` to call `ncremap` on PM and Chicoma

mpas_analysis/default.cfg, mpas_analysis/sea_ice/time_series.py
This allows us to mask out "bad" sea-ice cells that accumulate unphysical amounts of sea ice from the area, volume and mean thickness time series.
This is needed in order for us to produce useful analysis for the SORRM v2.1 simulations, where there is a cell with 90 km of sea ice(!!!) that we need to mask out.
=> Add support for maximum allowed sea-ice thickness

ci/recipe/meta.yaml, dev-spec.txt, docs/users_guide/config/regions.rst, docs/users_guide/tasks/regionalTSDiagrams.rst, mpas_analysis/default.cfg, mpas_analysis/ocean/ocean_regional_profiles.py, mpas_analysis/polar_regions.cfg
Adds a default config section for Greenland regional TS Diagrams, hovmoller plots, and regional profiles. All new plots are off by default.
The option to designate 'all' regions in a regionGroup was added to the regional ocean profiles task.
=> Add Greenland shelf regions to ocean analysis tasks

mpas_analysis/ocean/plot_hovmoller_subtask.py
Sometimes (e.g. on very coarse meshes), there are no cells in a given region.  In such cases, it's better to drop the hovmoller plot eniterly than to have analysis fail.
=> Fix hovmoller plots for empty regions

ci/recipe/meta.yaml, dev-spec.txt, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
This PR skips NCO 5.2.6, which seems to have an issue in which `ncremap` is not producing the desired `_FillValue` attribute even when requested with the `--add_fill_value` flag.
This PR also restricts `numpy < 2.0` for now, since it appears that the MPAS-Tools function `write_netcdf()` is not compatible and an updated version of MPAS-Tools is not yet available to fix this.
fixes #1008
=> Fix masking of remapped MPAS climatology maps

mpas_analysis/ocean/plot_transect_subtask.py, mpas_analysis/shared/plot/colormap.py
The `matplotlib.cm.get_cmap()` function no longer exists and we should use `matplotlib.pyplot.get_cmap()` instead.
=> Fix `cm.get_cmap()` calls

mpas_analysis/ocean/conservation.py, mpas_analysis/shared/io/mpas_reader.py, mpas_analysis/shared/timekeeping/utility.py
Here, we add conservation plot types for all the ocean's mass flux terms.
=> Enhance ocean conservation task

dev-spec.txt, mpas_analysis/shared/io/utility.py
This got missed in #1011.
This merge also updates the constraint on `mpas_tools` to `>=0.34.1` to bring in some matplotlib fixes.
=> Fix `numpy.string_` --> `numpy.bytes_`

docs/users_guide/analysis_tasks.rst, docs/users_guide/tasks/climatologyMapHeatFluxes.rst, docs/users_guide/tasks/climatologyMapMassFluxes.rst, mpas_analysis/__main__.py, mpas_analysis/default.cfg, mpas_analysis/ocean/climatology_map_fluxes.py, mpas_analysis/shared/constants/constants.py
Add surface heat fluxes to ocean climatology tasks
=> Add surface heat fluxes to ocean climatology tasks

mpas_analysis/default.cfg, mpas_analysis/ocean/conservation.py, mpas_analysis/shared/io/mpas_reader.py, suite/setup.py
Since we have changed the output frequency for the conservation AM to daily https://github.com/E3SM-Project/E3SM/pull/6412, I have noticed that this causes a bug with time averaging. The time averaging config option `movingAveragePoints` assumes that the output frequency for all the time series tasks is the same. This PR introduces a factor of 30 to `movingAveragePoints` for the conservation task and fixes an issue with the time string correction for restarts.
=> Bug fixes for time series conservation task

docs/users_guide/tasks/timeSeriesTransport.rst, mpas_analysis/default.cfg, mpas_analysis/ocean/time_series_transport.py, mpas_analysis/polar_regions.cfg
Add Arctic Transects from branch https://github.com/milenaveneziani/geometric_features/tree/flipOSNAP_renameArcticTransectsTag of geometric features.
Separate all arctic transects from standard transects using transectGroup flag in config option `timeSeriesTransport`.
When running `mpas_analysis` without the flag `--polar_regions` only standard transects are plotted. All Arctic transects including the three new ones "Hudson Bay-Labrador Sea", "OSNAP section East" and "OSNAP section West"
are only plotted when `--polar_regions` is specified.
timeSeriesTransport split into transportGroups "Transport Transects" and "Arctic Transport Transects". By default all Arctic transects are removed from standard transects. 
User can specify the list of standard transects to plot with transectsToPlot …
=> Add OSNAP Arctic Transects transport time series

README.md, ci/recipe/meta.yaml, docs/tutorials/dev_add_task.rst, docs/tutorials/dev_getting_started.rst
In this PR I added a few flags to the `python -m pip install [-e] .` command. The flags are:
* `-vv` indicates very verbose output. This flag is used during the CI runs to help with debugging.
* `--no-deps` indicates that pip should not install runtime dependencies from PyPi.
* `--no-build-isolation` indicates that pip should not install build time dependencies from PyPi.
=> Update `pip install` flags in docs and CI

docs/conf.py
=> Update sphinx-multiversion config options

docs/users_guide/tasks/climatologyMapWoa.rst, docs/users_guide/tasks/regionalTSDiagrams.rst, docs/users_guide/tasks/timeSeriesOceanRegions.rst, mpas_analysis/default.cfg, mpas_analysis/obs/observational_datasets.xml, mpas_analysis/ocean/climatology_map_woa.py, mpas_analysis/ocean/regional_ts_diagrams.py, mpas_analysis/ocean/time_series_ocean_regions.py, mpas_analysis/polar_regions.cfg, mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py, preprocess_observations/preprocess_woa23.py
This PR adds a preprocessing script for WOA23 and updates 3 analysis tasks, `climatologyMapWoa`, `timeSeriesOceanRegions` and `regionalTSDiagrams`, to use WOA23 instead of WOA18.
The observational database and documentation have also been updated.
Checklist
=> Switch from WOA18 to WOA23

mpas_analysis/sea_ice/climatology_map_berg_conc.py, mpas_analysis/sea_ice/climatology_map_melting.py, mpas_analysis/sea_ice/climatology_map_production.py, mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py, mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py, mpas_analysis/shared/plot/plot_climatology_map_subtask.py
The comparison grid name is confusing and redundant.
Checklist
=> Remove the comparison grid name from sea ice gallery groups

ci/recipe/meta.yaml, dev-spec.txt, docs/conf.py, docs/users_guide/config/regions.rst, mpas_analysis/default.cfg, mpas_analysis/polar_regions.cfg
This merge requires geometric_features 1.6.0, where a breaking change was made that renamed Greenland Regions to ISMIP6 Greenland Regions for clarity.  (NASA Greenland Regions were also added.)
This merge also fixes an issue with the docs in which the intersphinx link to MPAS-Tools is corrected (stable --> master).
Checklist
=> Rename Greenland Regions --> ISMIP6 Greenland Regions

docs/users_guide/tasks/timeSeriesOceanRegions.rst, mpas_analysis/default.cfg, mpas_analysis/ocean/time_series_ocean_regions.py
=> Add OHC anomaly to `timeSeriesOceanRegions`

.github/workflows/build_workflow.yml, .github/workflows/docs_workflow.yml, ci/python3.9.yaml, pyproject.toml
In this PR, I fixed a few minor issues:
1. The docs CI workflow was trying to reference a nonexistent variable to set the python version. I've changed this to reference a variable local to this file which will have to be manually changed if we want to build the docs in a later version of python (it's currently set to 3.10).
2. The build workflow was being skipped in relation to changes made in the `setup.py` file, but this should have been changed to `pyproject.toml` during #1044  
3. I added the `fail-fast` attribute to the build workflow so that jobs won't cancel other jobs if they fail, which will allow for more precise debugging for different python versions.
4. Some settings related to code linting were added during #1044 and should not have been as we don't have `pre-commit` set up …
=> Cleanup and minor CI bug fixes

ci/recipe/meta.yaml, dev-spec.txt
We don't have reason at this point to expect incompatibilities in future 8.x.x releases
Checklist
=> Relax upper bound on ESMF

.github/workflows/build_workflow.yml
This PR updates the build workflow to use separate directories for each python version for conda caching. Issues with this seem to have been crashing CI runs lately.
=> Use separate conda cache directories in CI

mpas_analysis/shared/plot/climatology_map.py
Without this fix, we were seeing:
```
File "/gpfs/fs1/home/ac.xylar/mpas_work/MPAS-Analysis/add_OSNAP_TSclimtransects/mpas_analysis/shared/plot/climatology_map.py", line 615, in plot_panel
for collection in cs.collections:
^^^^^^^^^^^^^^
AttributeError: 'GeoContourSet' object has no attribute 'collections'
```
in the logs for barotropic streamfuncion plot tasks.
Checklist
=> Fix barotropic streamfuncion

docs/tutorials/dev_getting_started.rst, docs/users_guide/tasks/antshipTransects.rst, docs/users_guide/tasks/climatologyMapSeaIceAlbedoNH.rst, docs/users_guide/tasks/climatologyMapSeaIceVolumeTendencyThermoNH.rst, docs/users_guide/tasks/climatologyMapSeaIceVolumeTendencyThermoSH.rst, docs/users_guide/tasks/climatologyMapSeaIceVolumeTendencyTranspNH.rst, docs/users_guide/tasks/climatologyMapSeaIceVolumeTendencyTranspSH.rst, docs/users_guide/tasks/osnapTransects.rst, mpas_analysis/obs/observational_datasets.xml
Some RST files have incorrect title underlining (good reason to switch to Markdown!).
Some link names were not quite right.
Some other formatting issues needed attention.
Checklist
=> Fix several errors in the docs

mpas_analysis/shared/html/image_xml.py, mpas_analysis/shared/html/pages.py, mpas_analysis/shared/html/templates/component_image.html, mpas_analysis/shared/html/templates/component_quicklink.html
This will hopefully reduce load time and server load.
This merge also changes the threshold on the aspect ratio of images at which images are considered "vertical" (and therefore given substantially taller thumbnails).  Before, the threshold was 1, meaning nearly square figures could end up with substantially larger or smaller size depending on tiny variations in width, which made galleries of squarish figures quite inconsistent.  The threshold is now set to 0.75 (i.e. 3:4).  Weird behavior could still be seen with figures near this aspect ratio but we don't currently have figures like that in our galleries.  (There are technical and aesthetic reasons that it is necessary to specify a fixed height for horizontal and vertical figures, rather than, for example, constraining either the …
=> Switch to writing thumbnails as jpgs

mpas_analysis/__main__.py
=> Raise error if mpas_analysis is installed in different worktree

suite/run_dev_suite.bash, suite/run_e3sm_unified_suite.bash, suite/run_suite.bash, suite/setup.py, suite/wc_defaults.cfg
These now match the main branch on zppy (what we expect to see in zppy 3.0.0).
=> Update water cycle defaults in test suite

docs/developers_guide/api.rst, docs/users_guide/config/regions.rst, docs/users_guide/tasks/timeSeriesOHCAnomaly.rst, docs/users_guide/tasks/timeSeriesSST.rst, docs/users_guide/tasks/timeSeriesSalinityAnomaly.rst, docs/users_guide/tasks/timeSeriesTemperatureAnomaly.rst, mpas_analysis/default.cfg, mpas_analysis/ocean/compute_anomaly_subtask.py, mpas_analysis/ocean/index_nino34.py, mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py, mpas_analysis/ocean/plot_hovmoller_subtask.py, mpas_analysis/ocean/time_series_ohc_anomaly.py, mpas_analysis/ocean/time_series_salinity_anomaly.py, mpas_analysis/ocean/time_series_sst.py, mpas_analysis/ocean/time_series_temperature_anomaly.py, mpas_analysis/ocean/utility.py
Two MPAS-Ocean analysis members use ocean regions that are hard-coded and for which no coordinate array or other metadata is provided.  This merge adds both `regionNames` and `regionShortNames` coordinates to datasets that use these standard regions.  Here, we also rename `nOceanRegionsTmp` to `nOceanRegions` because the `Tmp` suffix is confusing and needless.
All analysis using the hard-coded ocean regions has been updated.  The config option `regions` has been renamed to `regionShortNames` for clarity, and `plotTitle` has been renamed to `regionNames`, since these long names are more rightly the names of the regions.
This should help folks that wish to use the NetCDF output from MPAS-Analysis for their own plots.
Checklist
Fixes #1065
=> Add `regionNames` coordinate to NetCDF output with "standard" region names

mpas_analysis/ocean/conservation.py, mpas_analysis/ocean/meridional_heat_transport.py, mpas_analysis/shared/climatology/mpas_climatology_task.py, mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py, mpas_analysis/shared/time_series/mpas_time_series_task.py, mpas_analysis/shared/time_series/time_series.py
This clean-up PR also switches from `find_executable()` from `distutil` (which is deprecated) with `shutil.which()`.
Checklist
=> Set `decode_timedelta=False` to avoid future warnings in `xarray.open_dataset()` calls

mpas_analysis/default.cfg, mpas_analysis/shared/climatology/comparison_descriptors.py, mpas_analysis/shared/projection/__init__.py, suite/template.cfg
Adds the option to make plots on a grid that focuses on the Filchner-Ronne cavity.
Here is an example bsf plot with that option:
=> Add FRIS comparison grid

mpas_analysis/shared/plot/inset.py
The previous code seems to cause trouble with GEOS v3.13.1 (just releases).
Checklist
=> Fix inset bounds

mpas_analysis/ocean/conservation.py
This alternative approach makes sure the contents are unique (and sorted) in the `xtime` variable.
To reduce redundancy between the new approach and the old `ncrcat` approach (retained for comparison and in case the `xarray` approach is not performant), a new helper function for determining if we want to append to the existing datasets added.
Checklist
=> Alternative xarray approach to computing convservation time series

mpas_analysis/ocean/conservation.py
When recomputing the conservation analysis (e.g. in a main vs. control run or if analysis successfully ran previously), we can end up with an empty list of remaining inputs to process.  In this case, we should just move on rather than trying to print the empty list.
Checklist
=> Fix conservation when list of inputs is empty

mpas_analysis/ocean/climatology_map_bsf.py
If not, delete climatology and start fresh
Checklist
fixes #1078
=> Check that all BSF projections are present

docs/users_guide/tasks/climatologyMapSeaIceConcNH.rst, docs/users_guide/tasks/climatologyMapSeaIceConcSH.rst, docs/users_guide/tasks/climatologyMapSeaIceThickNH.rst, docs/users_guide/tasks/climatologyMapSeaIceThickSH.rst, mpas_analysis/default.cfg, mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py, mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py
This merge sets `extend` to `both`, rather than `neither` for difference plots of sea-ice concentration and thickness.  The previous value of `neither` led to plots like this one:
In this PR have slightly updated the indices into the colormap and explicitly added indices for the unser/over (not necessary but there for clarity).
Checklist
Fixes #1082
=> Set under/over indices for sea ice conc and thickness

mpas_analysis/ocean/conservation.py
A recent change (#1080) switched to using xarray to concatinate ocean conservation data together.  However, recent testing showed hangs if the datasets are not manually loaded.  This merge adds 2 places where such manual loads are included.
Checklist
=> Fix hangs in ocean conservation

ci/recipe/meta.yaml, dev-spec.txt, mpas_analysis/ocean/climatology_map_bsf.py
This allows us to use the same functionality in MPAS-Analysis and Polaris.  It also brings in the bug fix from https://github.com/MPAS-Dev/MPAS-Tools/pull/621 that implemented proper boundary conditions.
Checklist
=> Switch to using barotropic streamfunction from `mpas_tools`

mpas_analysis/ocean/plot_transect_subtask.py
Following #1092, the observational data on some transects is transposed compared with that from the model, leading to problems when plotting both together as contours.  This merge fixes the issue by transposing observations to match the model.
Checklist
=> Transpose transect obs dims to match model dims

docs/developers_guide/releasing.rst
This pull request updates the release process documentation in `docs/developers_guide/releasing.rst` to clarify version bump procedures, dependency updates, and conda-forge feedstock management. The changes aim to streamline the release workflow and ensure consistency across steps.
* Clarified that version numbers must be manually updated in `mpas_analysis/version.py` and `ci/recipe/meta.yaml`, with examples for release candidates (e.g., `1.3.0rc1`).
* Simplified dependency update instructions, emphasizing the use of the GitHub "Compare" feature to identify changes between releases.
* Added detailed steps for tagging releases on GitHub, including generating release notes and marking pre-releases when applicable.
* Introduced a preferred method for automatic feedstock updates via the …
=> Update the releasing documentation

ci/recipe/meta.yaml, dev-spec.txt, mpas_analysis/shared/io/write_netcdf.py
This PR also drops unlimited_dims if they aren't in the dataset.  Both of these updates are intended to handle a recent regression in `xarray` in which `unlimited_dims` present in the encoding dictionary but not in the dataset itself raise an error.  This frequently occurs when slicing the `Time` dimension in MPAS datasets.
Checklist
=> Update to mpas_tools >=1.3.0
