- README.md
Adds Continuous Integration badge to readme (as well as readme cleanup)
> Adds CI badge

- config.analysis
- mpas_analysis/ocean/ocean_modelvsobs.py
- mpas_analysis/ocean/ohc_timeseries.py
- mpas_analysis/ocean/sst_timeseries.py
- mpas_analysis/sea_ice/modelvsobs.py
- mpas_analysis/sea_ice/timeseries.py
- mpas_analysis/shared/io/namelist_streams_interface.py
- mpas_analysis/shared/timekeeping/Date.py
- mpas_analysis/test/test_date.py
- mpas_analysis/test/test_namelist_streams_interface.py
- mpas_analysis/test/test_namelist_streams_interface/streams.ocean
- run_analysis.py
This merge reads parameters from the namelist (instead of from NetCDF attributes) and
paths for model output to be analyzed from the streams file instead of hard coding them.
This merge also adds the ability to read a list of files that match a template from the streams
file (`StreamsFile.readpath`).  Optionally, the list of files can be restricted to lie between a
startDate and endDate.
Two new options, `analysis_start_date` and `analysis_end_date` have been added to the config
file (and given default values of `0001-01-01_00:00:00` and `9999-12-31_23:59:59`, respectively).
These values can be modified to allow analysis of a subset of output files (e.g. for debugging).
> Read paths from streams and config from namelist

- mpas_analysis/configuration/MpasAnalysisConfigParser.py
- mpas_analysis/test/test_mpas_config_parser.py
This is the lost commit from #50 following an incomplete merge.
> Add elementType flag to getExpression

- mpas_analysis/sea_ice/variable_stream_map.py
- mpas_analysis/shared/mpas_xarray/mpas_xarray.py
- mpas_analysis/shared/timekeeping/Date.py
This merge provides capability for MPAS-Analysis to work with MPAS-Seaice version v4.0-930-g6bbf734.
> Update Seaice variables for timeseries

- mpas_analysis/shared/mpas_xarray/mpas_xarray.py
Fixes lack of vim markers around functions (BFB).
> Adds vim markers to functions for consistency

- mpas_analysis/test/__init__.py
- mpas_analysis/test/test_date.py
- mpas_analysis/test/test_interpolate.py
- mpas_analysis/test/test_io_utility.py
- mpas_analysis/test/test_mpas_xarray.py
- mpas_analysis/test/test_namelist_streams_interface.py
This merge removes unneeded fixture and white space from a few tests.  This is BFB and only affects testing.
> Clean up tests

- configs/lanl/config.20170120.beta0.GMPAS-QU240.wolf
Turn on all analyses now that we have a remapping file for the
QU240km grid.
> Update generate option for G240km on LANL IC

- design_docs/generalized_horizontal_interpolation.md
Adds a design document describing generalized horizontal interpolation.
> Design Document: Generalized Horizontal Interpolation

- mpas_analysis/ocean/ohc_timeseries.py
- mpas_analysis/ocean/sst_timeseries.py
- mpas_analysis/sea_ice/timeseries.py
- mpas_analysis/shared/plot/plotting.py
They are now consistent with the calendar being used and they don't disappear for long time series, as they did before.
> Fix tick marks on the x axis of time series plots

- config.default
- mpas_analysis/sea_ice/timeseries.py
- mpas_analysis/shared/constants/constants.py
- mpas_analysis/shared/plot/plotting.py
This PR adds the option to plot the sea ice time series on a polar plot. This should aid visualization for very long simulations. As a newbie developer here I didn't know whether this is the right way to approach the coding for this enhancement, so am open to suggestions.
> Add option to plot sea ice time series on polar plots

- mpas_analysis/sea_ice/modelvsobs.py
- mpas_analysis/sea_ice/utility.py
The path should be relative to base directory, not run directory.
> Fix path to ocean streams file in sea ice utility

- mpas_analysis/ocean/nino34_index.py
In the current version of the NINO diagnostic, the detrending happens
separate from the computation of the index.  Thus the output index is
not detrended in the time series plot when it should be.  This fixes that issue by moving the
detrending from the spectra routine to the index routine.
> Fixes detrending of NINO34 index

- config.default
- mpas_analysis/ocean/meridional_heat_transport.py
- mpas_analysis/ocean/variable_stream_map.py
- mpas_analysis/shared/plot/plotting.py
- run_analysis.py
Add the ability to read and average MHT from the MHT analysis member output, plot 1D and 2D MHT.
> Meridional Heat Transport climatology and plots

- mpas_analysis/shared/climatology/climatology.py
- mpas_analysis/shared/io/utility.py
- mpas_analysis/test/test_climatology.py
Cleans up climatology test and removes the sleep command by finger printing climatology files.
> Refractors climatology tests and removes sleep command

- design_docs/parallel_tasks.md
This design document gives requirements, design and testing for how to introduce task parallelism into MPAS-Analysis.
> Design Document: Task parallelism

- README.md
- ci/requirements-py27.yml
- docs/environment.yml
- readthedocs.yml
This merge adds capabilities needed to automatically build the documentation on Read The Docs.
> Add environment for Read The Docs

- mpas_analysis/ocean/streamfunction_moc.py
- mpas_analysis/ocean/time_series_ohc.py
- mpas_analysis/ocean/time_series_sst.py
- mpas_analysis/sea_ice/time_series.py
- mpas_analysis/shared/plot/plotting.py
Reformatted OHC time series plot as well as other time series plots (SST, MOC and sea-ice).
Added a legendText to `timeseries_analysis_plot` and `timeseries_analysis_plot_polar`.
This is to address #229.
> Reformatted OHC and other time series plots

- mpas_analysis/sea_ice/climatology_map.py
All 4 sea-ice climatology map tasks were generating the same
files when calling ncclimo.  Now, each generates its own.
> Each sea-ice clim. task generates its own clim.

- mpas_analysis/ocean/index_nino34.py
There is a problem with using `numpy.datetime64` with the latest `numpy` as an x axis in plots.  Therefore, time is now expressed as days since `0001-01-01` (same as for model output).
A bit of layout clean-up was required to accommodate the fix.
A bit of code and docstring clean up was performed along the way.
> Fix time axis in Nino observations for numpy 1.13.3

- configs/edison/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison
- configs/edison/config.20171102.beta3rc02_1850.ne30_oECv3_ICG.edison
- mpas_analysis/ocean/streamfunction_moc.py
To support the beta3 run, for the moment, we need to use the offline MOC even if when the MOC AM is turned on.
> Switch to a new Edison beta2 and beta3 EC60to30 example runs

- docs/api.rst
- docs/index.rst
- mpas_analysis/configuration/MpasAnalysisConfigParser.py
- mpas_analysis/shared/analysis_task.py
- mpas_analysis/shared/climatology/climatology.py
- mpas_analysis/shared/io/namelist_streams_interface.py
- mpas_analysis/shared/io/utility.py
> Clean up docstrings and documentaiton

- mpas_analysis/ocean/time_series_ohc.py
- mpas_analysis/shared/plot/plotting.py
Otherwise the plot with pluses can become indistinguishable from a thick line.
> Plot no more than 300 pluses in OHC plot

- mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py
It was going into the sea-ice concentration gallery by mistake
> Fix the name of the gallery group for sea-ice thickness

- docs/mpasseaice.rst
Minor modifications to MPAS-Seaice documentation
> Minor modifications to MPAS-Seaice documentation

- mpas_analysis/config.default
- mpas_analysis/ocean/__init__.py
- mpas_analysis/ocean/climatology_map_argo.py
- mpas_analysis/ocean/climatology_map_sose.py
- mpas_analysis/ocean/remap_depth_slices_subtask.py
- mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
- run_mpas_analysis
this is a first cut at implementing the ability to compare against argo with depth.  The data is from Roemmich-Gilson Argo Climatology (http://sio-argo.ucsd.edu/RG_Climatology.html).  I've moved data to nersc for testing.  I would appreciate any suggestions.
> Add ability to MPAS to argo with depth

- docs/authors.rst
Reorder the authors alphabetically.
> Add Charles as a coauthor

- mpas_analysis/shared/climatology/ref_year_mpas_climatology_task.py
Oops!  Didn't do proper python2 testing!
> Fix bug in importing StringIO

- mpas_analysis/ocean/streamfunction_moc.py
- mpas_analysis/sea_ice/time_series.py
The bounds were previously being ignored and the full time range was being loaded, which is not the correct behavior if he time bounds have been diminished.
> Fix bounds on sea-ice time series from cache file

- mpas_analysis/config.default
- mpas_analysis/obs/observational_datasets.xml
- mpas_analysis/ocean/__init__.py
- mpas_analysis/ocean/climatology_map_schmidtko.py
- mpas_analysis/ocean/plot_climatology_map_subtask.py
- preprocess_observations/preprocess_Schmidtko_data.py
- run_mpas_analysis
A new processing script has been added to download and preprocess the observations.  The observations have also been added to the database, though I still need to find out the policy from Schmidtko.
> Add task to plot Bottom PT, S and PD against Schmidtko et al. (2014) observations

- configs/edison/config.20180514.G.oQU240wLI.edison
This run is useful for quick tests of the full analysis.
> Remove old QU240 run, add new QU240wLI on edison

- mpas_analysis/obs/make_obs_readme_bibtex.py
- mpas_analysis/obs/observational_datasets.xml
This merge also adds subdirectories to observational database. These are used to know where to put each data set along with its corresponding README and bibtex file.
>  Add a script for generating README and bibtex files for each obs. dataset

- README.md
- docs/.gitignore
- docs/conf.py
- docs/index.rst
- docs/parse_quick_start.py
This merge also makes some updates to the README:
* ACME --> E3SM
* Improved instructions for installing
* Moved developer-related details to the developer section
> Add README.md to the documentation as a quick start guide

- configs/theta/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta
Obs were moved to a location shared across E3SM projects
> Update obs in theta config file

- mpas_analysis/config.default
Color maps for many analysis tasks have been updated, following a group discusion
> Update default color maps

- docs/tasks/climatologyMapSosePotentialDensity.rst
This merge adds a file to the docs that was recently forgotten.
> Add climatologyMapSosePotentialDensity to docs

- mpas_analysis/shared/html/templates/style.css
With this merge, padding should work across browsers.
> Fix padding above provenance

- mpas_analysis/shared/climatology/mpas_climatology_task.py
With this merge, climatologies are successfully for individual months (Jan, Jul, etc.)
> Fix climatology computations with single months

- README.md
Just a quick fix to move the badge in the readme from latest to develop
> fix docs badge

- mpas_analysis/shared/climatology/ref_year_mpas_climatology_task.py
This fixes an issue where user defined choices of anomalyRefYear are not read due to a small typo.
addresses #441
> Fixes bug in climatology anomalyRefYear

- utility_scripts/make_mpas_to_Antarctic_stereo_mapping.py
This is very similar to the utility for making MPAS to lat/lon mapping files but for Antarctic stereographic grids.
> Add a utility for making an MPAS to Antarctic mapping file

- configs/lanl/config.BGCphaeo4.testrun
- configs/lanl/config.GMPAS-OECO-ODMS-IAF.oRRS30to10v3
- mpas_analysis/config.default
- mpas_analysis/ocean/climatology_map_bgc.py
- run_mpas_analysis
This should make it easier to compute a table of skill scores for all the requested BGC in a future merge.
> Refactor BGC so it is one task, not one per field

- readthedocs.yml
> Update RTD build to support python 3.6

- docs/analysis_tasks.rst
- docs/design_docs/eddykineticenergy.md
- docs/tasks/climatologyMapBGC.rst
- mpas_analysis/config.default
Also fixes some formatting issues with some other docs and the BGC config options.
Removes unused startYear, endYear config options for climatologyMapBGC
> Add climatologyMapBGC to docs

- README.md
- docs/api.rst
- docs/conf.py
- docs/design_docs/analysis_task_template.md
- docs/design_docs/config_file_reorganization.md
- docs/design_docs/parallel_tasks.md
- docs/design_docs/variable_mapping_reorg.md
- docs/environment.yml
- docs/index.rst
- docs/parse_quick_start.py
Convert .md files to .rst
Many formatting fixes to accommodate this.
Restore autogenerated API
closes #468
> Switch to m2r instead of recommonmark

- mpas_analysis/shared/grid/grid.py
Add a 2D lat/lon grid descriptor
These changes were needed for ISMIP6, which uses the same grid.py
closes #457
> Fix detecting periodic lat/lon descriptors

- README.md
- ci/requirements.yml
- conda/recipe/meta.yaml
- docs/api.rst
- mpas_analysis/__main__.py
- mpas_analysis/config.default
- mpas_analysis/ocean/time_series_antarctic_melt.py
- mpas_analysis/shared/html/pages.py
- mpas_analysis/shared/regions/__init__.py
- mpas_analysis/shared/regions/compute_region_masks_subtask.py
One subtask computes time series data for all ice shelves, while the remaining subtasks each plot the time series for an individual ice shelf.
> Split TimeSeriesAntarcticMelt into multiple subtasks

- mpas_analysis/ocean/time_series_antarctic_melt.py
- mpas_analysis/shared/plot/plotting.py
Also, fix a bug from #483 that led to obs not being plotted.
closes #488
> Enhance "error bars" for observations in Antarctic melt time series plots

- conda/recipe/meta.yaml
> Reset the build number to zero

- configs/plots/config.drake_contours
- mpas_analysis/config.default
- mpas_analysis/ocean/woce_transects.py
- mpas_analysis/shared/interpolation/interp_1d.py
- preprocess_observations/compute_woce_transects.py
This will allow plots of potential density across the Drake Passage, potentially useful for calibrating eddy parameterizations.
closes #230
>  Add potential density to WOCE transect plots

- configs/lanl/config.CONUS.100km.NAEC60to30cr8.20181218
- mpas_analysis/ocean/climatology_map_eke.py
Also adds a new CONUS example config file
> Fix typo in EKE analysis

- conda/recipe/meta.yaml
A few small changes based on what I learned about best practices today.
> Update the conda recipe with a little clean-up

- README.md
- docs/conf.py
Fix README.md and test import issue
> Try to figure out error in ReadTheDocs imports

- README.md
- docs/conf.py
- docs/environment.yml
- readthedocs.yml
Same recent fixes to the docs but on master (since this is what everyone sees).
> Update ReadTheDocs on master

- mpas_analysis/config.default
- mpas_analysis/ocean/plot_transect_subtask.py
- mpas_analysis/ocean/woce_transects.py
This makes it possible to focus on a subsection of a transect, which is often more useful for scientific analysis.
closes #537
> Update WOCE transects to allow x min and max

- configs/cori/config.20190225.GMPAS-DIB-IAF-ISMF.T62_oEC60to30v3wLI.cori-knl
This PR adds a new config file for Cori-KNL.
> Adding new config file for run on Cori-KNL.

- mpas_analysis/shared/plot/plotting.py
If the x axis gets bounds, the lat/lon at the top now reflect this.
closes #546
> Fix lat/lon axis limits for WOCE with bounds

- README.md
The `README.md` didn't get updated completely after the move to conda-forge
> Switch to conda-forge and mpas-analysis package in README

- README.md
- ci/requirements.yml
- docs/environment.yml
The basemap package has been fixed so it now includes this constraint.
> Remove proj4 requirement and constraint

- configs/alcf/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta
- configs/alcf/config.20180410.A_WCYCL1950_HR.ne120_oRRS18v3_ICG.theta
- configs/alcf/config.20190301.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta
- configs/alcf/job_script.cooley.18to6.bash
- configs/alcf/job_script.cooley.30to10.bash
The name of the E3SM project has changed.
> Update path in ALCC example conf files

- docs/config/execute.rst
- mpas_analysis/config.default
- mpas_analysis/shared/analysis_task.py
- mpas_analysis/shared/climatology/mpas_climatology_task.py
This should help with big data sets on cooley, where we've been running out of memory.
> Add support and docs for ncclimo "mpi" mode

- mpas_analysis/ocean/time_series_antarctic_melt.py
Analysis is performed in chunks of 1 year and 10 regions.
> Use chunking to reduce memory for Antarctic Melt time series

- mpas_analysis/__main__.py
- mpas_analysis/config.default
- mpas_analysis/ocean/__init__.py
- mpas_analysis/ocean/climatology_map_mld_min_max.py
- mpas_analysis/ocean/meridional_heat_transport.py
- mpas_analysis/ocean/plot_climatology_map_subtask.py
- mpas_analysis/ocean/streamfunction_moc.py
- mpas_analysis/sea_ice/plot_climatology_map_subtask.py
- mpas_analysis/shared/climatology/climatology.py
- mpas_analysis/shared/climatology/mpas_climatology_task.py
- mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
- mpas_analysis/shared/io/namelist_streams_interface.py
- mpas_analysis/test/test_mpas_climatology_task.py
Plots are made for min, max and max-min of the MLD based on temperature and density thresholds as well as the boundary-layer depth.
closes #573
> Add climatology maps for min/max mixed-layer depth

- mpas_analysis/ocean/ocean_regional_profiles.py
- mpas_analysis/ocean/plot_hovmoller_subtask.py
- mpas_analysis/ocean/time_series_antarctic_melt.py
- mpas_analysis/ocean/time_series_ocean_regions.py
- mpas_analysis/shared/io/__init__.py
- mpas_analysis/shared/io/utility.py
- mpas_analysis/shared/io/write_netcdf.py
- mpas_analysis/shared/time_series/mpas_time_series_task.py
Without this, python 3 can't read string data written out in python 2.
Fix resulting decoding in some tasks.
> Write string data as unicode in NetCDF files

- docs/environment.yml
Hopefully, this will help with memory issues on RTD
> Update docs environment to use pip as much as possible

- docs/environment.yml
> Update env for RTD

- README.md
- download_natural_earth_110m.py
- mpas_analysis/__main__.py
- mpas_analysis/config.default
- mpas_analysis/ocean/time_series_ocean_regions.py
- setup.py
Also, include zmin/zmax in the plot title
> Allow zmin/zmax for ocean regions from config file

- README.md
- ci/requirements.yml
The argument issue to ncclimo in 4.8.0 has been resolved.
> Update to nco>=4.8.1

- README.md
@xylar, this is in response to https://github.com/MPAS-Dev/MPAS-Analysis/pull/597. This PR simply adds a few lines to the README for how to get natural earth to work on clusters that can't download the shape files (e.g., IC at LANL).
> Add natural earth instructions to README for issues with downloading

- mpas_analysis/ocean/climatology_map_antarctic_melt.py
- mpas_analysis/ocean/climatology_map_schmidtko.py
- mpas_analysis/ocean/climatology_map_sose.py
- mpas_analysis/ocean/sose_transects.py
- mpas_analysis/ocean/time_series_antarctic_melt.py
- mpas_analysis/ocean/time_series_ocean_regions.py
- mpas_analysis/sea_ice/climatology_map_berg_conc.py
- mpas_analysis/sea_ice/climatology_map_sea_ice_conc.py
- mpas_analysis/sea_ice/climatology_map_sea_ice_thick.py
- mpas_analysis/sea_ice/time_series.py
This help if one wants to enable only tasks in these regions, or disable them.
closes #602
> Add 'antarctic' and 'arctic' tags to tasks

- mpas_analysis/__main__.py
- mpas_analysis/shared/html/pages.py
- mpas_analysis/shared/html/templates/main_page.html
- mpas_analysis/shared/html/templates/style.css
Also add command line to provenance
closes #601
> Add custom config file to webpage

- mpas_analysis/shared/html/templates/config.html
> Add missing config.html template

- configs/compy/config.20190711.testLuke.A_WCYCL1850S.ne30_oECv3.compy
- configs/compy/job_script.compy.bash
adds compy config file and job script file.  
closes #598
> Adds sample config and jobscript file for compy

- mpas_analysis/config.default
- mpas_analysis/ocean/time_series_ocean_regions.py
The plot title needs to be different, so an attribute needs to be stored to know vol. vs. area averages.
closes #636
> Fix compute/plot of regional time series of 2D ocean vars.

- configs/olcf/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison
- configs/olcf/config.20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison
- configs/olcf/config.GMPAS-IAF_oRRS18to6v3.titan
This has been out of date for quite some time.
> Update diagnostics path on olcf

- configs/polarRegions.conf
- mpas_analysis/config.default
Include them in `configs/polarRegions.conf` instead.
closes #664
> Disable various Arctic/Antarctic tasks by default

- configs/anvil/config.SO60to10ISC.20200108
- configs/anvil/job_script.anvil.bash
> Update example config file and job script for anvil

- README.md
- mpas_analysis/ocean/regional_ts_diagrams.py
They were hanging during write, causing trouble.  The change is to compute, write, and read back 
data sets at various stages. Hopefully this will prevent half-written files that are showing up as all fill values.
> Make obs TS climatologies more robust

- mpas_analysis/ocean/meridional_heat_transport.py
- mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py
- mpas_analysis/ocean/streamfunction_moc.py
- mpas_analysis/ocean/time_series_antarctic_melt.py
- mpas_analysis/ocean/time_series_ocean_regions.py
- mpas_analysis/ocean/time_series_sst.py
- mpas_analysis/ocean/time_series_transport.py
- mpas_analysis/sea_ice/time_series.py
- mpas_analysis/shared/plot/time_series.py
- mpas_analysis/shared/plot/vertical_section.py
This should given better clarity.
> Rename N to movingAveragePoints in plotting

- mpas_analysis/__main__.py
- mpas_analysis/config.default
- mpas_analysis/ocean/climatology_map_antarctic_melt.py
The melt rates and fluxes are computed from seasonal climatologies. Melt rates are averaged and melt fluxes are integrated over each ice shelf or region.
The results are written out to a csv file that isn't very easy to find.  Eventually, it could be included on the web page but the idea for now is that it's available for inclusion in papers and such where the data would need to be reformatted anyway.
> Write out a cvs table of Antarctic melt rates/fluxes

- configs/cori/config.20171201.default.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl
- configs/cori/config.20180129.DECKv1b_piControl.ne30_oEC.edison
- configs/cori/config.20180209.GMPAS-IAF.T62_oRRS30to10v3wLI.cori-knl.afterSalinityFix
- configs/cori/config.20180511.GMPAS-IAF.T62_oEC60to30v3wLI.edison
- configs/cori/config.20180514.G.oQU240wLI.edison
- configs/cori/config.20190225.GMPAS-DIB-IAF-ISMF.T62_oEC60to30v3wLI.cori-knl
- configs/cori/config.B_low_res_ice_shelves_1696_JWolfe_layout_Edison
- configs/cori/job_script.cori-haswell.bash
- configs/cori/job_script.cori-knl.bash
- configs/plots/config.drake_contours
> Change path to e3sm project on NERSC

- mpas_analysis/ocean/climatology_map_antarctic_melt.py
...by only reading geojson files if the analysis is actually being run (preventing reading non-existent files).
closes #699
> Fix --list flag

- mpas_analysis/shared/plot/climatology_map.py
Before, ice shelves were not filled in in these plots.
> Add ice shelves to global and sea-ice plots

- README.md
Causing install issues for @darincomeau and @stephenprice.
> Fix missing quotes in example install in README

- mpas_analysis/ocean/streamfunction_moc.py
> Fix GM namelist option for MOC

- docs/tasks/timeSeriesAntarcticMelt.rst
- docs/tasks/timeSeriesOceanRegions.rst
- docs/tasks/timeSeriesTransport.rst
- mpas_analysis/config.default
- mpas_analysis/ocean/time_series_antarctic_melt.py
- mpas_analysis/ocean/time_series_ocean_regions.py
- mpas_analysis/ocean/time_series_transport.py
This merge removes dask from several time-series tasks that were hanging from time to time.
> Remove dask from time series tasks

- docs/versions.rst
- mpas_analysis/__init__.py
- setup.py
This merge just bumps the version number for the next release.
> Update version to 1.2.7

- mpas_analysis/config.default
The config option was changed in the code and in some config files but not in the default.
> Fix movingAveragePoints --> movingAverageMonths for hovmoller

- README.md
This adds one documentation page describing possible ways to customize plots and also the metadata that is generated by MPAS-Analaysis when climatology and time series tasks are activated.
> Update documentation to describe possible customizations

- azure-pipelines.yml
- ci/recipe/meta.yaml
- docs/versions.rst
- mpas_analysis/__init__.py
- setup.py
> Update version to 1.2.8

- mpas_analysis/shared/plot/climatology_map.py
This adds the globally-computed mean and std values of the bias (either bias with respect to obs or difference with respect to the reference run) in the title of the third panel of the climatological map plot.
> Adds the globally-computed bias mean and rsme values in the title of climatological map plots

- README.md
The base isn't enough for what we want to do.
> Switch from matplotlib-base to full matplotlib

- README.md
The markdown wasn't quite right.
> Fix azure badge in README

- mpas_analysis/config.default
- mpas_analysis/ocean/time_series_ocean_regions.py
We added these observations for figures in the Cryosphere v1 paper and it seems like they would be useful in general.
> Add WOA18 and SOSE obs. to time series of ocean regions

- mpas_analysis/config.default
- mpas_analysis/ocean/climatology_map_antarctic_melt.py
Also, fix selecting of single Time level.
> Send melt tables to "tables" directory

- configs/anvil/job_script.anvil.bash
- configs/chrysalis/job_script.chrysalis.bash
- configs/chrysalis/test_suite/QU480.cfg
- configs/chrysalis/test_suite/clean_suilte.bash
- configs/chrysalis/test_suite/ctrl.cfg
- configs/chrysalis/test_suite/job_script.bash
- configs/chrysalis/test_suite/job_script_no_polar_regions.bash
- configs/chrysalis/test_suite/main.cfg
- configs/chrysalis/test_suite/main_vs_ctrl.cfg
- configs/chrysalis/test_suite/no_ncclimo.cfg
- configs/chrysalis/test_suite/test_suite.bash
There are small differences compared with Anvil.
> Add job script and test suite for chrysalis

- mpas_analysis/shared/plot/climatology_map.py
The statistics are now in text boxes to the right, similar to E3SM_Diags.
closes #767
> Add more statistics to global climatology maps

- README.md
- azure-pipelines.yml
- ci/python3.9.yaml
- ci/recipe/meta.yaml
This merge also fixes some typos in the README file.
> Update python version to >=  3.7

- configs/anvil/test_suite/job_script.bash
- configs/anvil/test_suite/job_script_no_polar_regions.bash
- configs/anvil/test_suite/main_vs_ctrl.cfg
- configs/anvil/test_suite/test_suite.bash
- configs/chrysalis/test_suite/job_script.bash
- configs/chrysalis/test_suite/job_script_no_polar_regions.bash
- configs/chrysalis/test_suite/test_suite.bash
- docs/config/input.rst
- docs/design_docs.rst
- docs/tasks/hovmollerOceanRegions.rst
- docs/tasks/regionalTSDiagrams.rst
- docs/tasks/timeSeriesOceanRegions.rst
This should hopefully prevent some conflicts between runs that were causing core dumps.
This merge also includes some fixes to the documentation where `:ref:` tags were incorrect or out of date.
> Update test suites so each test run is in its own directory

- mpas_analysis/ocean/regional_ts_diagrams.py
- mpas_analysis/ocean/time_series_ocean_regions.py
The region group should probably remain capitalized, rather than having the first letter converted to lower case.  This is particularly true for the ISMIP6 region group, which will be added in #777.
> Fix capitalization

- README.md
- ci/recipe/meta.yaml
- mpas_analysis/ocean/streamfunction_moc.py
- mpas_analysis/shared/regions/compute_region_masks_subtask.py
Use the python mask functions and add date stamps to the files.
This requires newer versions of both `mpas_tools` and `geometric_features`.
> Create MOC masks like other region masks

- mpas_analysis/ocean/ocean_regional_profiles.py
This should eliminate out-of-memory errors that have been happening.
closes #787
> Iterate over region masks in oceanRegionalProfile sums

- mpas_analysis/config.default
- mpas_analysis/ocean/time_series_transport.py
- mpas_analysis/shared/plot/colormap.py
- mpas_analysis/shared/transects/compute_transect_masks_subtask.py
These are new in geometric_features.  They are hand-drawn so there are no associated obs.
> Add 2 new transects to transport time series

- README.md
- configs/README.md
- configs/alcf/job_script.cooley.18to6.bash
- configs/alcf/job_script.cooley.30to10.bash
- configs/compy/job_script.compy.bash
- configs/compy/test_suite/job_script.bash
- configs/compy/test_suite/job_script_no_polar_regions.bash
- configs/cori/job_script.cori-haswell.bash
- configs/cori/job_script.cori-knl.bash
- configs/cori/test_suite/job_script.bash
- configs/cori/test_suite/job_script_no_polar_regions.bash
- configs/job_script.default.bash
- configs/lanl/job_script.lanl.bash
- configs/lcrc/job_script.anvil.bash
- configs/lcrc/job_script.chrysalis.bash
- configs/lcrc/test_suite/anvil/job_script.bash
- configs/lcrc/test_suite/anvil/job_script_no_polar_regions.bash
- configs/lcrc/test_suite/chrysalis/job_script.bash
- configs/lcrc/test_suite/chrysalis/job_script_no_polar_regions.bash
- configs/olcf/job_script.olcf.bash
- dev_environment.yaml
With this change, you can set up an environment for using the latest code from `develop` with:
```
conda create -n mpas_dev
conda activate mpas_dev
conda env update -n mpas_dev -f ./dev_environment.yaml
python -m pip install -e .
```
If you make changes to the local branch, they will be reflected immediately when you run `mpas_analysis` from the command line. No need for `python -m mpas_analysis`.  No need to keep track of using the right list of packages from the README, they are all in the yaml file.
The example job scripts and the README have been updated to reflect this change.
> Add a yaml file for building a dev environment

- docs/config/plot.rst
- mpas_analysis/config.default
- mpas_analysis/ocean/index_nino34.py
- mpas_analysis/ocean/meridional_heat_transport.py
- mpas_analysis/ocean/ocean_regional_profiles.py
- mpas_analysis/ocean/plot_depth_integrated_time_series_subtask.py
- mpas_analysis/ocean/plot_hovmoller_subtask.py
- mpas_analysis/ocean/plot_transect_subtask.py
- mpas_analysis/ocean/regional_ts_diagrams.py
- mpas_analysis/ocean/streamfunction_moc.py
- mpas_analysis/ocean/time_series_antarctic_melt.py
- mpas_analysis/ocean/time_series_ocean_regions.py
- mpas_analysis/ocean/time_series_sst.py
- mpas_analysis/ocean/time_series_transport.py
- mpas_analysis/sea_ice/time_series.py
- mpas_analysis/shared/plot/climatology_map.py
- mpas_analysis/shared/plot/oned.py
- mpas_analysis/shared/plot/save.py
- mpas_analysis/shared/plot/vertical_section.py
This is useful for making figures for papers, particularly if they need to be edited afterward.
> Add support for writing out pdfs in addition to pngs

- mpas_analysis/shared/plot/climatology_map.py
Switch from meridians every 60 to every 30 degrees.  Remove weird ticks on the vertical axes.
> Adjust cartopy grid lines

- mpas_analysis/__main__.py
- mpas_analysis/config.default
- mpas_analysis/ocean/__init__.py
- mpas_analysis/ocean/time_series_ssh_anomaly.py
- mpas_analysis/shared/time_series/anomaly.py
The SSH anomaly is equivalent to the anomaly in the global mean water-column thickness:
```
meanWaterColumnThickness = volumeCellGlobal / areaCellGlobal
```
since the global area of the ocean is fixed in time.
closes #811
> Add analysis task for computing a global mean SSH anomaly

- ci/recipe/meta.yaml
- configs/lcrc/20201025.GMPAS-IAF.T62_oQU240wLI.anvil.cfg
- dev-spec.txt
- mpas_analysis/config.default
- mpas_analysis/shared/climatology/climatology.py
- mpas_analysis/test/test_climatology.py
- mpas_analysis/test/test_mpas_climatology_task/config.QU240
- mpas_analysis/test/test_remap_obs_clim_subtask/config.remap_obs
The latest E3SM-Unified supports using system ESMF, which requires that ESMF gets run with `srun`.
> Add mapParallelExec config option

- azure-pipelines.yml
This got missed in a previous update
> Update xarray-master test on Azure to latest ubuntu

- mpas_analysis/__main__.py
It was failing because of a missing config option
> Fix list command

- mpas_analysis/shared/climatology/mpas_climatology_task.py
We can not supply an input directory for this NCO version, we need to provide input file names relative to the current working directory.
> Fix calls to ncclimo for NCO 5.0.4

- docs/config/output.rst
- example.cfg
- example_e3sm.cfg
- mpas_analysis/ocean/climatology_map_ohc_anomaly.py
- mpas_analysis/ocean/time_series_ohc_anomaly.py
- mpas_analysis/ocean/time_series_salinity_anomaly.py
- mpas_analysis/ocean/time_series_ssh_anomaly.py
- mpas_analysis/ocean/time_series_temperature_anomaly.py
- mpas_analysis/shared/climatology/ref_year_mpas_climatology_task.py
This should make it easier to turn off analysis in situations where a reference year isn't available.
closes #844
> Add an `anomaly` tag

- ci/recipe/meta.yaml
- docs/versions.rst
- mpas_analysis/__init__.py
> Update to v1.7.2

- azure-pipelines.yml
This should hopefully speed up CI considerably.
> Switch to using mamba and mambabuild in Azure

- mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
- mpas_analysis/shared/projection/__init__.py
These are causing errors in the docs.
> Fix some docstrings

- README.md
The description of how to build the documentation was badly outdated, and has been update.
> Fix description of building the docs

- docs/users_guide/tasks/oceanHistogram.rst
Resolves formatting error in ocean histogram documentation.
> Fixup formatting in histogram documentation

- mpas_analysis/ocean/climatology_map_schmidtko.py
We need to rename `x <---> y` for the Schmidtko observations.  This hasn't been an issue up to now because we happened to be using square comparison grids but causes trouble when `len(x) != len(y)`, as in the FRIS comparison grid we're using for a paper.
> Fix coordinate order for Schmidtko seafloor T and S

- ci/recipe/meta.yaml
- dev-spec.txt
- setup.py
There is a bug with tight layouts and insets
https://github.com/matplotlib/matplotlib/pull/26291
> Don't use matplotlib 3.7.2

- ci/recipe/meta.yaml
- dev-spec.txt
- mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py
- mpas_analysis/test/test_climatology.py
This requires using `MpasCellMeshDescriptor` and `MpasVertexMeshDescriptor` instead of `MpasMeshDescriptor`.
> Update to pyremap>=1.2.0

- mpas_analysis/ocean/time_series_antarctic_melt.py
This was a change I forgot to push in #989
> Fix Adusumilli variable name

- azure-pipelines.yml
- ci/python3.12.yaml
Also, switch from python 3.9 to 3.12 for testing.
> Update CI to drop mamba

- ci/recipe/meta.yaml
- dev-spec.txt
- mpas_analysis/ocean/index_nino34.py
- setup.py
This is used in the El Nino 3.4 analysis.
> Fix tukey import in latest scipy

- mpas_analysis/default.cfg
- mpas_analysis/ocean/ocean_regional_profiles.py
- mpas_analysis/polar_regions.cfg
Mask `oceanRegionalProfiles` tasks by bottom depth.
> Mask ocean regional profiles by bottom depth

- README.md
- docs/conf.py
> More fixes to sphinx multiversion

- mpas_analysis/ocean/conservation.py
Include land ice frazil in land ice mass terms of the ocean conservation task
Checklist
> Fix land ice frazil in ocean conservation task

- .github/pull_request_template.md
- docs/tutorials/dev_add_task.rst
- docs/tutorials/dev_getting_started.rst
- docs/tutorials/dev_understand_a_task.rst
- docs/tutorials/getting_started.rst
- docs/users_guide/config/climatology.rst
- example.cfg
- example_e3sm.cfg
- mpas_analysis/default.cfg
This merge fixes issues, primarily with the tutorial for developers, related to the documentation.
Checklist
> Several fixes to the docs

- suite/run_dev_suite.bash
- suite/run_e3sm_unified_suite.bash
- suite/run_suite.bash
- suite/setup.py
It doesn't add value over the QU240wLI test we use and it may be too old to be useful.
Checklist
> Remove the QU480 test from the test suite

- ci/recipe/meta.yaml
- dev-spec.txt
This is really important because MPAS-Tools 1.0.0 will have several breaking changes.
Checklist
> Constrain mpas_tools <1.0.0

- mpas_analysis/polar_regions.cfg
This merge also changes the order of the galleries to make more sense.
This was already tested in #1069
> Update Arctic and add North Atlantic BSF config options

- MANIFEST.in
- ci/recipe/meta.yaml
> Add missing colormaps

- dev-spec.txt
- pyproject.toml
In this PR, I've separated the optional and required dependencies into different categories to exclude developer tools from the required dependencies. I also cleaned up some unnecessary packages that were listed in `dev-spec.txt` but not actually used.
Checklist
> Separate dependencies in `pyproject.toml`

- mpas_analysis/ocean/climatology_map_bsf.py
This seems to be necessary, at least at high res, to not run out of memory.
Checklist
> Reserve all processes for BSF calculation

- mpas_analysis/ocean/conservation.py
- mpas_analysis/polar_regions.cfg
These are the variables we want to BlueTip, which seems like a good reason we should want them for polar regions generally (at least for now).
Checklist
> Expand variables for polar regions conservation and mass fluxes

- mpas_analysis/default.cfg
- mpas_analysis/ocean/climatology_map_custom.py
- mpas_analysis/ocean/remap_depth_slices_subtask.py
- suite/main.cfg
- suite/setup.py
This pull request introduces several updates to the MPAS-Analysis codebase, including configuration adjustments, bug fixes, and new features for climatology map customization. The key changes focus on improving variable handling, fixing typos, enhancing functionality for derived variables, and adding new configuration options.
* Fixed a typo in the variable name `verlocityMagnitude` to `velocityMagnitude` and updated its title in `mpas_analysis/default.cfg` to "Velocity Magnitude" for consistency. [[1]](diffhunk://#diff-48912753959c46a241b1c94e258c086f0d3b01b37497553da903a486c9392033L2205-R2205) [[2]](diffhunk://#diff-c305a12f0fc4016042616f136bbbc648b56783a188c2c37a2157a455ec6620faL298-R305)
* Replaced `timeMonthly_avg_activeTracers_layerThickness` with `timeMonthly_avg_layerThickness` in …
> Fix custom climatology maps

- .github/dependabot.yml
This PR just adds @andrewdnolan to the dependabot reviewer list
@xylar Review checklist:
> Add @andrewdnolan to dependabot reviewers

- suite/main.cfg
It is not available in the test model run.
Checklist
> Remove icebergFreshWaterFlux from test suite
